use std::fmt::Write;
use std::path::Path;

#[derive(Clone)]
struct Route {
    group_prefix: String,
    module_path: String,
    handler: String,
}

#[allow(clippy::cast_precision_loss)]
fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let backend_root = Path::new(&manifest_dir);
    let router_root = backend_root.join("src").join("router");

    println!("cargo:rerun-if-changed=src/router");
    println!("cargo:rerun-if-changed=src/lib.rs");

    let all_routes = collect_all_routes(&router_root);
    let mut annotated: Vec<Route> = Vec::new();
    let mut missing: Vec<&Route> = Vec::new();

    for r in &all_routes {
        if has_annotation(r, backend_root) {
            annotated.push(Route {
                group_prefix: r.group_prefix.clone(),
                module_path: r.module_path.clone(),
                handler: r.handler.clone(),
            });
        } else {
            missing.push(r);
        }
    }

    for r in &missing {
        println!(
            "cargo:warning=missing #[utoipa::path] annotation on {}::{}",
            r.module_path, r.handler
        );
    }

    if !all_routes.is_empty() {
        let annotated_count = annotated.len();
        let total = all_routes.len();
        if annotated_count != total {
            let coverage_pct = (annotated_count as f64 / total as f64) * 100.0;
            println!(
                "cargo:warning=utoipa annotation coverage: {:.1}% ({}/{})",
                coverage_pct, annotated_count, total
            );
        }
    }

    generate_openapi_rs(&annotated, &backend_root.join("src").join("openapi.rs"));
}

fn generate_openapi_rs(annotated: &[Route], dest: &Path) {
    let group_order: [&str; 5] = ["get", "post", "put", "delete", "fairing"];
    let mut annotated = annotated.to_vec();
    annotated.sort_by(|a, b| {
        let a_grp = group_order
            .iter()
            .position(|&g| g == a.group_prefix)
            .unwrap_or(99);
        let b_grp = group_order
            .iter()
            .position(|&g| g == b.group_prefix)
            .unwrap_or(99);
        a_grp
            .cmp(&b_grp)
            .then_with(|| a.module_path.cmp(&b.module_path))
            .then_with(|| a.handler.cmp(&b.handler))
    });

    let mut out = String::new();
    writeln!(out, "// Auto-generated by build.rs. Do not edit manually.").unwrap();
    writeln!(out, "use utoipa::OpenApi;").unwrap();
    writeln!(out).unwrap();

    for r in &annotated {
        let import_mod = if r.module_path == r.group_prefix {
            format!("crate::router::{g}", g = r.group_prefix)
        } else {
            format!(
                "crate::router::{g}::{m}",
                g = r.group_prefix,
                m = r.module_path
            )
        };
        writeln!(
            out,
            "use {import_mod}::__path_{handler};",
            import_mod = import_mod,
            handler = r.handler
        )
        .unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "#[derive(OpenApi)]").unwrap();
    writeln!(out, "#[openapi(").unwrap();
    writeln!(out, "    paths(").unwrap();

    let mut current_group = String::new();
    for r in &annotated {
        let section = match r.group_prefix.as_str() {
            "get" => "// ── GET routes",
            "post" => "// ── POST routes",
            "put" => "// ── PUT routes",
            "delete" => "// ── DELETE routes",
            "fairing" => "// ── FAIRING routes",
            _ => "",
        };
        if section != current_group {
            if !current_group.is_empty() {
                writeln!(out).unwrap();
            }
            writeln!(out, "        {section}").unwrap();
            current_group = section.to_string();
        }
        writeln!(out, "        {},", r.handler).unwrap();
    }

    writeln!(out, "    ),").unwrap();
    writeln!(out, ")]").unwrap();
    writeln!(out, "pub struct ApiDoc;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[must_use]").unwrap();
    writeln!(out, "pub fn generate_json() -> String {{").unwrap();
    writeln!(out, "    ApiDoc::openapi()").unwrap();
    writeln!(out, "        .to_json()").unwrap();
    writeln!(out, "        .expect(\"OpenAPI serialization failed\")").unwrap();
    writeln!(out, "}}").unwrap();

    std::fs::write(dest, out.as_bytes()).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", dest.display());
    });
    // Do NOT rerun on dest — it's generated, would cause rebuild loop.
}

fn has_annotation(route: &Route, backend_root: &Path) -> bool {
    let source = if route.module_path == route.group_prefix {
        backend_root
            .join("src")
            .join("router")
            .join(format!("{}.rs", route.group_prefix))
    } else {
        backend_root
            .join("src")
            .join("router")
            .join(&route.group_prefix)
            .join(format!("{}.rs", route.module_path))
    };
    let Ok(content) = std::fs::read_to_string(&source) else {
        return false;
    };
    content.contains("utoipa::path") && content.contains(&format!("fn {}(", route.handler))
}

fn collect_all_routes(router_root: &Path) -> Vec<Route> {
    let mod_entries = [
        ("get", "get/mod.rs"),
        ("post", "post/mod.rs"),
        ("put", "put/mod.rs"),
        ("delete", "delete.rs"),
        ("fairing", "fairing/mod.rs"),
    ];

    let mut routes = Vec::new();

    for (group_prefix, rel_path) in &mod_entries {
        let path = router_root.join(rel_path);
        let Ok(content) = std::fs::read_to_string(&path) else {
            continue;
        };

        let mut search_start = 0usize;
        while let Some(routes_start) = content[search_start..].find("routes![") {
            let abs_start = search_start + routes_start;
            let body_start = abs_start + "routes![".len();
            let rest = &content[body_start..];
            if let Some(end) = find_matching_bracket(rest) {
                let block = &rest[..end];
                for line in block.lines() {
                    let trimmed = line.trim();
                    if trimmed.is_empty() || trimmed.starts_with("//") {
                        continue;
                    }
                    let entry = trimmed.strip_suffix(',').unwrap_or(trimmed).trim();
                    let entry = entry.strip_suffix(']').unwrap_or(entry).trim();
                    if entry.is_empty() {
                        continue;
                    }

                    let (mod_name, handler) = if let Some(pos) = entry.rfind("::") {
                        (entry[..pos].to_string(), entry[pos + 2..].to_string())
                    } else {
                        (group_prefix.to_string(), entry.to_string())
                    };

                    routes.push(Route {
                        group_prefix: group_prefix.to_string(),
                        module_path: mod_name,
                        handler,
                    });
                }
                search_start = body_start + end + 1;
            } else {
                break;
            }
        }
    }

    routes
}

fn find_matching_bracket(s: &str) -> Option<usize> {
    let mut depth = 0u32;
    for (i, ch) in s.char_indices() {
        match ch {
            '[' => depth += 1,
            ']' => {
                if depth == 0 {
                    return Some(i);
                }
                depth -= 1;
            }
            _ => {}
        }
    }
    None
}
