use std::collections::HashMap;
use std::path::{Path, PathBuf};

type VarMap = HashMap<String, String>;

pub fn generate_all() {
    let root = workspace_root();
    let api_dir = root.join("scenarios/api");
    let schema_path = root.join("scenarios/schema.json");
    let openapi_path = root.join("gallery-backend/openapi.json");
    let out_path = root.join("gallery-backend/src/tests/scenarios_generated.rs");

    let _schema: serde_json::Value =
        load_json(&schema_path).expect("failed to load scenarios/schema.json");
    let _openapi: serde_json::Value =
        load_json(&openapi_path).expect("failed to load gallery-backend/openapi.json");

    let mut modules: Vec<String> = Vec::new();

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&api_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", api_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .is_some_and(|ext| ext == "yaml" || ext == "yml")
        })
        .collect();
    entries.sort();

    for path in &entries {
        let yaml_str = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let scenario: serde_json::Value = serde_yaml::from_str(&yaml_str)
            .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

        let name = scenario["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{}: missing 'name'", path.display()));

        let test_fn = emit_api_test(name, &scenario);
        modules.push(test_fn);
    }

    let body = modules.join("\n\n");
    let generated = format!(
        "// @generated by xtask gen-scenarios -- do not edit.\n\
         // Re-generate with: cargo xtask gen-scenarios\n\
         \n\
         #![cfg(test)]\n\
         #![allow(clippy::module_inception, clippy::needless_borrows_for_generic_args)]\n\
         mod scenarios_generated {{\n\
             use crate::tests::fixtures::*;\n\
             use rocket::http::{{ContentType, Status}};\n\
         \n\
         {body}\n\
         }}\n"
    );

    std::fs::write(&out_path, &generated)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));

    // Post-process with rustfmt to ensure consistent formatting.
    let fmt_status = std::process::Command::new("rustfmt")
        .arg(&out_path)
        .status()
        .unwrap_or_else(|e| panic!("rustfmt failed: {e}"));
    if !fmt_status.success() {
        eprintln!(
            "warning: rustfmt returned non-zero status on {}",
            out_path.display()
        );
    }

    eprintln!("wrote {} ({} scenarios)", out_path.display(), modules.len());
}

fn emit_api_test(name: &str, scenario: &serde_json::Value) -> String {
    let fn_name = name
        .to_lowercase()
        .replace([' ', '-', '.', '/'], "_")
        .replace(|c: char| !c.is_ascii_alphanumeric() && c != '_', "")
        .trim_matches('_')
        .to_string();

    let given = scenario["given"].as_array();
    let when = &scenario["when"];
    let then = scenario["then"].as_array().expect("then must be an array");

    let mut vars: VarMap = HashMap::new();
    let mut lines: Vec<String> = Vec::new();

    // Check whether we need DATA_PATH (given items or filesystem assertions)
    let needs_data = given.map(|items| !items.is_empty()).unwrap_or(false)
        || then.iter().any(|item| {
            item.get("file_exists").is_some() || item.get("file_absent").is_some()
        });

    if needs_data {
        lines.push(
            "let data = {\n\
                 let _ = &*TEST_ENV;\n\
                 DATA_PATH.get().expect(\"DATA_PATH initialised\")\n\
             };"
            .to_string(),
        );
    }

    // Process given items
    if let Some(items) = given {
        for item in items {
            if let Some(dir) = item["dir_album"].as_str() {
                let v = fresh_var(&mut vars, item, "album");
                let trimmed = dir.trim_start_matches('/');
                lines.push(format!(
                    "std::fs::create_dir_all(&data.join(\"{trimmed}\")).expect(\"create album dir\");"
                ));
                lines.push(format!(
                    "let {v} = make_dir_album(&data.join(\"{trimmed}\"));"
                ));
            } else if let Some(photo) = item["photo"].as_str() {
                let v = fresh_var(&mut vars, item, "photo");
                let photo_relative = photo.trim_start_matches('/');
                let src_dir = Path::new(photo_relative)
                    .parent()
                    .map(|p| p.to_string_lossy())
                    .unwrap_or_default();

                if !src_dir.is_empty() && src_dir != "." {
                    lines.push(format!(
                        "std::fs::create_dir_all(&data.join(\"{src_dir}\")).expect(\"create dir\");"
                    ));
                }

                let has_color = item.get("color").and_then(|c| c.as_array()).is_some();

                if has_color {
                    let color = item["color"].as_array().unwrap();
                    let r = color[0].as_i64().unwrap_or(128);
                    let g = color[1].as_i64().unwrap_or(128);
                    let b = color[2].as_i64().unwrap_or(128);
                    lines.push(format!(
                        "write_real_jpeg(&data.join(\"{photo_relative}\"), [{r}, {g}, {b}]);"
                    ));
                } else {
                    lines.push(format!(
                        "std::fs::write(&data.join(\"{photo_relative}\"), b\"\\xff\\xd8\\xff fake jpeg\").expect(\"write source file\");"
                    ));
                }

                let tags: Vec<String> = item["tags"]
                    .as_array()
                    .map(|arr| {
                        arr.iter()
                            .map(|t| format!("\"{}\"", t.as_str().unwrap_or("unknown")))
                            .collect()
                    })
                    .unwrap_or_default();
                let tags_arr = if tags.is_empty() {
                    "&[]".to_string()
                } else {
                    format!("&[{}]", tags.join(", "))
                };
                let exif_date = item["exif_date"]
                    .as_str()
                    .map(|d| format!("Some({d:?})"))
                    .unwrap_or_else(|| "None".to_string());

                let has_var = item.get("id_as").is_some();
                if has_var {
                    lines.push(format!(
                        "let {v} = {{\n\
                             let src = data.join(\"{photo_relative}\");\n\
                             let hashes = insert_photos(&[PhotoSpec {{ path: src.to_str().unwrap(), tags: {tags_arr}, exif_date: {exif_date} }}]);\n\
                             hashes[0].clone()\n\
                         }};"
                    ));
                } else {
                    lines.push(format!(
                        "{{\n\
                             let src = data.join(\"{photo_relative}\");\n\
                             insert_photos(&[PhotoSpec {{ path: src.to_str().unwrap(), tags: {tags_arr}, exif_date: {exif_date} }}]);\n\
                         }}"
                    ));
                }

                vars.insert(photo.to_string(), v);
            }
        }
    }

    // Process when/then blocks
    let is_multi = when.is_array();

    if is_multi {
        let calls = when.as_array().expect("when array");
        let mut client_emitted = false;
        for (i, call) in calls.iter().enumerate() {
            let resp_var = format!("resp_{i}");
            emit_single_call(call, &vars, &mut lines, &resp_var, !client_emitted);
            client_emitted = true;

            if let Some(call_then) = call.get("then").and_then(|v| v.as_array()) {
                emit_then_assertions(call_then, &resp_var, &vars, &mut lines);
            }

            // Capture response fields into variables for subsequent steps.
            if let Some(capture) = call.get("capture").and_then(|c| c.as_object()) {
                if !capture.is_empty() {
                    lines.push(format!(
                        "let parsed_body: serde_json::Value =\n\
                             serde_json::from_slice(\n\
                                 &{resp_var}.into_bytes().expect(\"response body\")\n\
                             ).unwrap();"
                    ));
                    for (var_name, json_path) in capture {
                        let bare = var_name.trim_start_matches('$');
                        let field = json_path.as_str().unwrap_or_else(|| {
                            panic!("capture {var_name}: value must be a string JSON path")
                        });
                        let access = build_json_access(field);
                        lines.push(format!(
                            "let {bare} = {{\n\
                                 let val = &parsed_body{access};\n\
                                 val.as_str().map(|s| s.to_string())\n\
                                     .unwrap_or_else(|| val.to_string())\n\
                             }};"
                        ));
                        vars.insert(bare.to_string(), bare.to_string());
                    }
                }
            }

            // Compute derived values from captured variables.
            if let Some(calc) = call.get("calc").and_then(|c| c.as_object()) {
                for (var_name, expr) in calc {
                    let bare = var_name.trim_start_matches('$');
                    let expr_str = expr.as_str().unwrap_or_else(|| {
                        panic!("calc {var_name}: value must be a string expression")
                    });
                    // Support: "${var}+N" where N is a literal integer.
                    if let Some((var_part, suffix)) = expr_str.split_once('+') {
                        let var_part = var_part.trim_start_matches("${").trim_end_matches('}');
                        let suffix = suffix.trim();
                        if let Ok(n) = suffix.parse::<i64>() {
                            lines.push(format!(
                                "let {bare} = ({var_part}.parse::<i64>().unwrap() + {n}).to_string();"
                            ));
                            vars.insert(bare.to_string(), bare.to_string());
                        }
                    }
                }
            }
        }
        let last_resp = format!("resp_{}", calls.len().saturating_sub(1));
        emit_then_assertions(then, &last_resp, &vars, &mut lines);
    } else {
        emit_single_call(when, &vars, &mut lines, "resp", true);
        emit_then_assertions(then, "resp", &vars, &mut lines);
    }

    let body = lines.join("\n    ");
    format!(
        "#[test]\n\
         fn {fn_name}() {{\n\
             {body}\n\
         }}"
    )
}

fn emit_single_call(
    call: &serde_json::Value,
    vars: &VarMap,
    lines: &mut Vec<String>,
    resp_var: &str,
    emit_client: bool,
) {
    let call_str = call["call"].as_str().expect("when.call is required");
    let body_val = call.get("body");
    let auth = call.get("auth").and_then(|v| v.as_bool()).unwrap_or(true);

    let parts: Vec<&str> = call_str.splitn(2, ' ').collect();
    let method = parts[0];
    let path = parts[1];

    let body_str = body_val
        .map(|b| body_to_json_expr(b, vars))
        .unwrap_or_default();

    if emit_client {
        lines.push("let client = make_client();".to_string());
    }

    let method_lower = method.to_lowercase();
    let path_expr = if path.contains("${") {
        format!("format!(r#\"{}\"#)", substitute_path_vars(path, vars))
    } else {
        format!("\"{path}\"")
    };
    let mut req = format!("let {resp_var} = client\n    .{method_lower}({path_expr})");
    if auth {
        req.push_str("\n    .cookie(auth_cookie(&client))");
    }
    // Custom headers
    if let Some(headers) = call.get("headers").and_then(|h| h.as_object()) {
        for (hdr_name, hdr_val) in headers {
            let val_expr = value_to_json_expr(hdr_val, vars);
            req.push_str(&format!(
                "\n    .header(rocket::http::Header::new(\"{hdr_name}\", {val_expr}))"
            ));
        }
    }
    if method != "GET" {
        req.push_str("\n    .header(ContentType::JSON)");
        if !body_str.is_empty() {
            req.push_str(&format!("\n    .body({body_str})"));
        }
    }
    req.push_str("\n    .dispatch();");
    lines.push(req);
}

/// Convert a dotted JSON path like `response.prefetch.locateTo` or
/// `response.[0].tags` into Rust bracket access like
/// `["prefetch"]["locateTo"]` or `[0]["tags"]`.
fn build_json_access(path: &str) -> String {
    let stripped = path.strip_prefix("response.").unwrap_or(path);
    stripped
        .split('.')
        .map(|seg| {
            if let Some(idx) = seg.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                format!("[{idx}]")
            } else {
                format!("[{seg:?}]")
            }
        })
        .collect::<Vec<_>>()
        .join("")
}

fn substitute_path_vars(path: &str, vars: &VarMap) -> String {
    let mut result = String::new();
    let mut rest = path;
    while let Some(start) = rest.find("${") {
        result.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        if let Some(end) = after.find('}') {
            let var_name = &after[..end];
            let bare = var_name.trim_start_matches('$');
            if vars.contains_key(bare) {
                result.push_str(&format!("{{{bare}}}"));
            } else {
                result.push_str(&format!("${{{var_name}}}"));
            }
            rest = &after[end + 1..];
        } else {
            result.push_str("${");
            rest = after;
        }
    }
    result.push_str(rest);
    result
}

fn emit_then_assertions(
    then_items: &[serde_json::Value],
    resp_var: &str,
    vars: &VarMap,
    lines: &mut Vec<String>,
) {
    // First emit all status checks (before body is consumed).
    for item in then_items {
        if let Some(code) = item["response.status"].as_i64() {
            lines.push(format!(
                "assert_eq!({resp_var}.status(), Status::from_code({code}).unwrap(), \"call {resp_var} status\");"
            ));
        } else if let Some(code) = item["response.status_not"].as_i64() {
            lines.push(format!(
                "assert_ne!({resp_var}.status(), Status::from_code({code}).unwrap(), \"call {resp_var} must not return {code}\");"
            ));
        }
    }

    // Collect JSON-path assertions so we can parse the body once.
    let json_checks: Vec<(String, &serde_json::Value)> = then_items
        .iter()
        .filter_map(|item| {
            item.as_object().and_then(|m| m.iter().next()).and_then(
                |(key, val)| {
                    if key.starts_with("response.json.") || key == "array_min_counts" {
                        Some((key.clone(), val))
                    } else {
                        None
                    }
                },
            )
        })
        .collect();

    if !json_checks.is_empty() {
        lines.push(format!(
            "let parsed_final: serde_json::Value =\n\
                 serde_json::from_slice(\n\
                     &{resp_var}.into_bytes().expect(\"response body\")\n\
                 ).expect(\"valid JSON\");"
        ));
        for (key, val) in &json_checks {
            if key == "array_min_counts" {
                let pairs: Vec<String> = val
                    .as_object()
                    .unwrap()
                    .iter()
                    .map(|(tag, count)| {
                        let c = count.as_u64().unwrap_or(0);
                        format!("({tag:?}, {c}u64)")
                    })
                    .collect();
                lines.push(format!(
                    "let tags = parsed_final.as_array().expect(\"response must be an array\");\n\
                     for (tag, min) in [{}] {{\n\
                         let got = tags.iter()\n\
                             .find(|t| t[\"tag\"].as_str() == Some(tag))\n\
                             .and_then(|t| t[\"number\"].as_u64())\n\
                             .unwrap_or(0);\n\
                         assert!(got >= min, \"tag '{{tag}}': expected >= {{min}}, got {{got}}\");\n\
                     }}",
                    pairs.join(", ")
                ));
                continue;
            }
            let field_path = key.strip_prefix("response.json.").unwrap();
            let access = field_path
                .split('.')
                .map(|seg| {
                    if let Some(idx) = seg.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                        format!("[{idx}]")
                    } else {
                        format!("[{seg:?}]")
                    }
                })
                .collect::<Vec<_>>()
                .join("");
            if let Some(contained) = val.as_object().and_then(|o| o.get("contains")) {
                let contained_expr = value_to_json_expr(contained, vars);
                let contained_label = contained.as_str().unwrap_or("?");
                lines.push(format!(
                    "let arr = parsed_final{access}.as_array().expect(\"{key} must be an array\");\n\
                     assert!(arr.contains(&serde_json::json!({contained_expr})), \
                         \"{key} does not contain {contained_label}\");"
                ));
            } else {
                let expect = value_to_json_expr(val, vars);
                lines.push(format!(
                    "assert_eq!(parsed_final{access}, serde_json::json!({expect}), \"{key} mismatch\");"
                ));
            }
        }
    }

    // file_exists / file_absent assertions.
    for item in then_items {
        if let Some(file_path) = item["file_exists"].as_str() {
            let trimmed = file_path.trim_start_matches('/');
            lines.push(format!(
                "assert!(data.join(\"{trimmed}\").exists(), \"file should exist: {trimmed}\");"
            ));
        } else if let Some(file_path) = item["file_absent"].as_str() {
            let trimmed = file_path.trim_start_matches('/');
            lines.push(format!(
                "assert!(!data.join(\"{trimmed}\").exists(), \"file should be absent: {trimmed}\");"
            ));
        }
    }
}

fn fresh_var(vars: &mut VarMap, item: &serde_json::Value, prefix: &str) -> String {
    if let Some(id) = item["id_as"].as_str() {
        let bare = id.trim_start_matches('$');
        let code_name = bare.to_string();
        vars.entry(bare.to_string())
            .or_insert_with(|| code_name.clone());
        code_name
    } else {
        let idx = vars.len();
        let name = format!("{prefix}_{idx}");
        vars.insert(name.clone(), name.clone());
        name
    }
}

fn body_to_json_expr(val: &serde_json::Value, vars: &VarMap) -> String {
    match val {
        serde_json::Value::String(s) => {
            if let Some(bare) = s.strip_prefix("${").and_then(|s| s.strip_suffix('}')) {
                if let Some(rust_var) = vars.get(bare) {
                    rust_var.clone()
                } else {
                    format!("{bare:?}.to_string()")
                }
            } else {
                format!("{s:?}.to_string()")
            }
        }
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "serde_json::Value::Null".to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(|v| body_to_json_expr(v, vars)).collect();
            format!("vec![{}]", items.join(", "))
        }
        serde_json::Value::Object(map) => {
            let pairs: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("{k:?}: {}", body_to_json_expr(v, vars)))
                .collect();
            format!("serde_json::json!({{{}}}).to_string()", pairs.join(", "))
        }
    }
}

fn interpolate_string(s: &str, vars: &VarMap) -> String {
    if let Some(bare) = s.strip_prefix("${").and_then(|s| s.strip_suffix('}')) {
        if let Some(rust_var) = vars.get(bare) {
            return rust_var.clone();
        }
        return format!("{bare:?}");
    }

    let mut parts: Vec<String> = Vec::new();
    let mut rest = s;
    while let Some(start) = rest.find("${") {
        if let Some(end) = rest[start..].find('}') {
            let literal = &rest[..start];
            let bare = &rest[start + 2..start + end];
            if !literal.is_empty() {
                parts.push(format!("{literal:?}.to_string()"));
            }
            if let Some(rust_var) = vars.get(bare) {
                parts.push(format!("{rust_var}.clone()"));
            } else {
                parts.push(format!("{bare:?}"));
            }
            rest = &rest[start + end + 1..];
        } else {
            break;
        }
    }
    if !rest.is_empty() {
        parts.push(format!("{rest:?}.to_string()"));
    }

    if parts.is_empty() {
        return r#""".to_string()"#.to_string();
    }

    parts.join(" + &")
}

fn value_to_json_expr(val: &serde_json::Value, vars: &VarMap) -> String {
    match val {
        serde_json::Value::String(s) => interpolate_string(s, vars),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "null".to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(|v| value_to_json_expr(v, vars)).collect();
            format!("[{}]", items.join(", "))
        }
        serde_json::Value::Object(map) => {
            let pairs: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("{k:?}: {}", value_to_json_expr(v, vars)))
                .collect();
            format!("{{{pairs}}}", pairs = pairs.join(", "))
        }
    }
}

fn load_json(path: &Path) -> Result<serde_json::Value, String> {
    let content =
        std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_str(&content).map_err(|e| format!("parse {}: {e}", path.display()))
}

fn workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| {
        std::env::current_dir()
            .unwrap()
            .to_string_lossy()
            .to_string()
    }));
    loop {
        let manifest = dir.join("Cargo.toml");
        if manifest.exists() {
            let content = std::fs::read_to_string(&manifest).ok();
            if content
                .as_deref()
                .is_some_and(|c| c.contains("[workspace]"))
            {
                return dir;
            }
        }
        if !dir.pop() {
            panic!("workspace root not found");
        }
    }
}
