use std::collections::HashMap;
use std::path::{Path, PathBuf};

type VarMap = HashMap<String, String>;

pub fn generate_all() {
    let root = workspace_root();
    let backend_dir = root.join("xtask/data/scenarios/backend");
    let schema_path = root.join("xtask/data/schema.json");
    let openapi_path = root.join("gallery-backend/openapi.json");
    let out_path = root.join("gallery-backend/src/tests/scenarios_generated.rs");

    let schema: serde_json::Value =
        load_json(&schema_path).expect("failed to load xtask/data/schema.json");
    let _openapi: serde_json::Value =
        load_json(&openapi_path).expect("failed to load gallery-backend/openapi.json");

    let mut modules: Vec<String> = Vec::new();

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&backend_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", backend_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .is_some_and(|ext| ext == "yaml" || ext == "yml")
        })
        .collect();
    entries.sort();

    for path in &entries {
        let yaml_str = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let scenario: serde_json::Value = serde_yaml::from_str(&yaml_str)
            .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

        validate_scenario(&schema, &scenario, path);

        let name = scenario["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{}: missing 'name'", path.display()));

        let test_fn = emit_api_test(name, &scenario);
        modules.push(test_fn);
    }

    let body = modules.join("\n\n");
    let indented_body = indent_lines(&body, 4);
    let generated = format!(
        "// @generated by cargo xtask test-backend -- do not edit.\n\
         // Re-generate with: cargo xtask test-backend\n\
         \n\
         #![cfg(test)]\n\
         #![allow(clippy::module_inception, clippy::needless_borrows_for_generic_args)]\n\
         mod scenarios_generated {{\n\
         {}use crate::tests::fixtures::*;\n\
         {}use rocket::http::{{ContentType, Status}};\n\
         \n\
         {}\n\
         }}",
        "    ", "    ", indented_body
    );

    std::fs::write(&out_path, &generated)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));

    // Post-process with rustfmt to ensure consistent formatting.
    let fmt_status = std::process::Command::new("rustfmt")
        .arg(&out_path)
        .status()
        .unwrap_or_else(|e| panic!("rustfmt failed: {e}"));
    if !fmt_status.success() {
        eprintln!(
            "warning: rustfmt returned non-zero status on {}",
            out_path.display()
        );
    }

    eprintln!("wrote {} ({} scenarios)", out_path.display(), modules.len());
}

fn emit_api_test(name: &str, scenario: &serde_json::Value) -> String {
    let fn_name = scenario_fn_name(name);
    let raw_body = emit_api_test_body(name, scenario);
    let body = indent_lines(&raw_body, 4);
    format!(
        "#[test]\n\
         fn {fn_name}() {{\n\
         {body}\n\
         }}"
    )
}

fn emit_single_call(
    call: &serde_json::Value,
    vars: &VarMap,
    lines: &mut Vec<String>,
    resp_var: &str,
    emit_client: bool,
) {
    let call_str = call["call"].as_str().expect("when.call is required");
    let body_val = call.get("body");
    let auth = call.get("auth").and_then(|v| v.as_bool()).unwrap_or(true);

    let parts: Vec<&str> = call_str.splitn(2, ' ').collect();
    let method = parts[0];
    let path = parts[1];

    let body_str = if let Some(raw_body) = call.get("raw_body").and_then(|v| v.as_str()) {
        body_raw_to_expr(raw_body, vars)
    } else {
        body_val
            .map(|b| body_to_json_expr(b, vars))
            .unwrap_or_default()
    };

    if emit_client {
        lines.push("let client = make_client();".to_string());
    }

    let method_lower = method.to_lowercase();
    let path_expr = if path.contains("${") {
        format!("format!(r#\"{}\"#)", substitute_path_vars(path, vars))
    } else {
        format!("\"{path}\"")
    };
    let mut req = format!("let {resp_var} = client\n    .{method_lower}({path_expr})");
    if auth {
        req.push_str("\n    .cookie(auth_cookie(&client))");
    }
    // Custom headers
    if let Some(headers) = call.get("headers").and_then(|h| h.as_object()) {
        for (hdr_name, hdr_val) in headers {
            let val_expr = value_to_json_expr(hdr_val, vars);
            req.push_str(&format!(
                "\n    .header(rocket::http::Header::new(\"{hdr_name}\", {val_expr}))"
            ));
        }
    }
    if method != "GET" {
        req.push_str("\n    .header(ContentType::JSON)");
        if !body_str.is_empty() {
            req.push_str(&format!("\n    .body({body_str})"));
        }
    }
    req.push_str("\n    .dispatch();");
    lines.push(req);
}

/// Convert a `raw_body` template (using `${var}` references) into a Rust
/// `format!()` expression that interpolates the captured variables at test
/// runtime.  Literal `{` and `}` characters in the template are doubled
/// for Rust's format string syntax (e.g. JSON `{` → `{{`).
fn body_raw_to_expr(raw: &str, _vars: &VarMap) -> String {
    let mut fmt_parts: Vec<String> = Vec::new();
    let mut rest = raw;
    while let Some(start) = rest.find("${") {
        let literal = &rest[..start];
        fmt_parts.push(literal.replace('{', "{{").replace('}', "}}"));
        let after = &rest[start + 2..];
        if let Some(end) = after.find('}') {
            let var_name = &after[..end];
            let bare = var_name.trim_start_matches('$');
            fmt_parts.push(format!("{{{bare}}}"));
            rest = &after[end + 1..];
        } else {
            fmt_parts.push("${{".to_string());
            rest = after;
        }
    }
    fmt_parts.push(rest.replace('{', "{{").replace('}', "}}"));
    let fmt_str = fmt_parts.join("");
    format!("format!(r#\"{fmt_str}\"#)")
}

/// Convert a dotted JSON path like `response.prefetch.locateTo` or
/// `response.[0].tags` into Rust bracket access like
/// `["prefetch"]["locateTo"]` or `[0]["tags"]`.
fn build_json_access(path: &str) -> String {
    let stripped = path.strip_prefix("response.").unwrap_or(path);
    stripped
        .split('.')
        .map(|seg| {
            if let Some(idx) = seg.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                format!("[{idx}]")
            } else {
                format!("[{seg:?}]")
            }
        })
        .collect::<Vec<_>>()
        .join("")
}

fn substitute_path_vars(path: &str, vars: &VarMap) -> String {
    let mut result = String::new();
    let mut rest = path;
    while let Some(start) = rest.find("${") {
        result.push_str(&rest[..start]);
        let after = &rest[start + 2..];
        if let Some(end) = after.find('}') {
            let var_name = &after[..end];
            let bare = var_name.trim_start_matches('$');
            if vars.contains_key(bare) {
                result.push_str(&format!("{{{bare}}}"));
            } else {
                result.push_str(&format!("${{{var_name}}}"));
            }
            rest = &after[end + 1..];
        } else {
            result.push_str("${");
            rest = after;
        }
    }
    result.push_str(rest);
    result
}

fn emit_then_assertions(
    then_items: &[serde_json::Value],
    resp_var: &str,
    vars: &VarMap,
    lines: &mut Vec<String>,
) {
    // First emit all status checks (before body is consumed).
    for item in then_items {
        if let Some(code) = item["response.status"].as_i64() {
            lines.push(format!(
                "assert_eq!({resp_var}.status(), Status::from_code({code}).unwrap(), \"call {resp_var} status\");"
            ));
        } else if let Some(code) = item["response.status_not"].as_i64() {
            lines.push(format!(
                "assert_ne!({resp_var}.status(), Status::from_code({code}).unwrap(), \"call {resp_var} must not return {code}\");"
            ));
        }
    }

    // Collect JSON-path assertions so we can parse the body once.
    let json_checks: Vec<(String, &serde_json::Value)> = then_items
        .iter()
        .filter_map(|item| {
            item.as_object().and_then(|m| m.iter().next()).and_then(
                |(key, val)| {
                    if key.starts_with("response.json.")
                        || key == "array_min_counts"
                        || key == "array_where"
                    {
                        Some((key.clone(), val))
                    } else {
                        None
                    }
                },
            )
        })
        .collect();

    if !json_checks.is_empty() {
        lines.push(format!(
            "let parsed_final: serde_json::Value =\n\
                 serde_json::from_slice(\n\
                     &{resp_var}.into_bytes().expect(\"response body\")\n\
                 ).expect(\"valid JSON\");"
        ));
        for (key, val) in &json_checks {
            if key == "array_min_counts" {
                let pairs: Vec<String> = val
                    .as_object()
                    .unwrap()
                    .iter()
                    .map(|(tag, count)| {
                        let c = count.as_u64().unwrap_or(0);
                        format!("({tag:?}, {c}u64)")
                    })
                    .collect();
                lines.push(format!(
                    "let tags = parsed_final.as_array().expect(\"response must be an array\");\n\
                     for (tag, min) in [{}] {{\n\
                         let got = tags.iter()\n\
                             .find(|t| t[\"tag\"].as_str() == Some(tag))\n\
                             .and_then(|t| t[\"number\"].as_u64())\n\
                             .unwrap_or(0);\n\
                         assert!(got >= min, \"tag '{{tag}}': expected >= {{min}}, got {{got}}\");\n\
                     }}",
                    pairs.join(", ")
                ));
                continue;
            }
            if key == "array_where" {
                let aw = val.as_object().expect("array_where value must be an object");
                let where_obj = aw.get("where").and_then(|w| w.as_object()).expect("array_where requires 'where' object");
                let assert_obj = aw.get("assert").and_then(|a| a.as_object()).expect("array_where requires 'assert' object");
                let where_pairs: Vec<String> = where_obj.iter()
                    .map(|(field, cond)| {
                        let cond_expr = value_to_json_expr(cond, vars);
                        format!("item[{field:?}] == serde_json::json!({cond_expr})")
                    })
                    .collect();
                lines.push(format!(
                    "let found = parsed_final.as_array().expect(\"response must be an array\").iter()\n\
                         .find(|item| {})\n\
                         .expect(\"no element matching array_where conditions\");",
                    where_pairs.join(" && "),
                ));
                for (field, expected) in assert_obj {
                    let expect_expr = value_to_json_expr(expected, vars);
                    lines.push(format!(
                        "assert_eq!(found[{field:?}], serde_json::json!({expect_expr}), \"array_where {field} mismatch\");"
                    ));
                }
                continue;
            }
            let field_path = key.strip_prefix("response.json.").unwrap();
            let access = field_path
                .split('.')
                .map(|seg| {
                    if let Some(idx) = seg.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                        format!("[{idx}]")
                    } else {
                        format!("[{seg:?}]")
                    }
                })
                .collect::<Vec<_>>()
                .join("");
            if let Some(contained) = val.as_object().and_then(|o| o.get("contains")) {
                let contained_expr = value_to_json_expr(contained, vars);
                let contained_label = contained.as_str().unwrap_or("?");
                lines.push(format!(
                    "let arr = parsed_final{access}.as_array().expect(\"{key} must be an array\");\n\
                     assert!(arr.contains(&serde_json::json!({contained_expr})), \
                         \"{key} does not contain {contained_label}\");"
                ));
            } else if val
                .as_object()
                .and_then(|o| o.get("all_absolute"))
                .and_then(|v| v.as_bool())
                == Some(true)
            {
                lines.push(format!(
                    "for child in parsed_final{access}.as_array().expect(\"{key} must be an array\") {{\n\
                         let path = child.as_str().expect(\"child must be a string\");\n\
                         assert!(std::path::Path::new(path).is_absolute(), \
                             \"expected absolute path, got {{path}}\");\n\
                     }}"
                ));
            } else {
                let expect = value_to_json_expr(val, vars);
                lines.push(format!(
                    "assert_eq!(parsed_final{access}, serde_json::json!({expect}), \"{key} mismatch\");"
                ));
            }
        }
    }

    // file_exists / file_absent assertions.
    for item in then_items {
        if let Some(file_path) = item["file_exists"].as_str() {
            let trimmed = file_path.trim_start_matches('/');
            lines.push(format!(
                "assert!(data.join(\"{trimmed}\").exists(), \"file should exist: {trimmed}\");"
            ));
        } else if let Some(file_path) = item["file_absent"].as_str() {
            let trimmed = file_path.trim_start_matches('/');
            lines.push(format!(
                "assert!(!data.join(\"{trimmed}\").exists(), \"file should be absent: {trimmed}\");"
            ));
        } else if let Some(photo_var) = item["serve_image_ok"].as_str() {
            let bare = photo_var.trim_start_matches('$');
            let rust_var = vars
                .get(bare)
                .unwrap_or_else(|| panic!("serve_image_ok: unknown var {photo_var}"));
            lines.push(format!(
                "assert_eq!(serve_compressed_image(&client, &{rust_var}), Status::Ok, \
                 \"serve_image_ok: {photo_var}\");"
            ));
        }
    }
}

fn fresh_var(vars: &mut VarMap, item: &serde_json::Value, prefix: &str) -> String {
    if let Some(id) = item["id_as"].as_str() {
        let bare = id.trim_start_matches('$');
        let code_name = bare.to_string();
        vars.entry(bare.to_string())
            .or_insert_with(|| code_name.clone());
        code_name
    } else {
        let idx = vars.len();
        let name = format!("{prefix}_{idx}");
        vars.insert(name.clone(), name.clone());
        name
    }
}

fn body_to_json_expr(val: &serde_json::Value, vars: &VarMap) -> String {
    match val {
        serde_json::Value::String(s) => {
            if let Some(bare) = s.strip_prefix("${").and_then(|s| s.strip_suffix('}')) {
                if let Some(rust_var) = vars.get(bare) {
                    rust_var.clone()
                } else {
                    format!("{bare:?}.to_string()")
                }
            } else {
                format!("{s:?}.to_string()")
            }
        }
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "serde_json::Value::Null".to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(|v| body_to_json_expr(v, vars)).collect();
            format!("vec![{}]", items.join(", "))
        }
        serde_json::Value::Object(map) => {
            let pairs: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("{k:?}: {}", body_to_json_expr(v, vars)))
                .collect();
            format!("serde_json::json!({{{}}}).to_string()", pairs.join(", "))
        }
    }
}

fn interpolate_string(s: &str, vars: &VarMap) -> String {
    if let Some(bare) = s.strip_prefix("${").and_then(|s| s.strip_suffix('}')) {
        if let Some(rust_var) = vars.get(bare) {
            return rust_var.clone();
        }
        return format!("{bare:?}");
    }

    let mut parts: Vec<String> = Vec::new();
    let mut rest = s;
    while let Some(start) = rest.find("${") {
        if let Some(end) = rest[start..].find('}') {
            let literal = &rest[..start];
            let bare = &rest[start + 2..start + end];
            if !literal.is_empty() {
                parts.push(format!("{literal:?}.to_string()"));
            }
            if let Some(rust_var) = vars.get(bare) {
                parts.push(format!("{rust_var}.clone()"));
            } else {
                parts.push(format!("{bare:?}"));
            }
            rest = &rest[start + end + 1..];
        } else {
            break;
        }
    }
    if !rest.is_empty() {
        parts.push(format!("{rest:?}.to_string()"));
    }

    if parts.is_empty() {
        return r#""".to_string()"#.to_string();
    }

    parts.join(" + &")
}

fn value_to_json_expr(val: &serde_json::Value, vars: &VarMap) -> String {
    match val {
        serde_json::Value::String(s) => interpolate_string(s, vars),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "null".to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(|v| value_to_json_expr(v, vars)).collect();
            format!("[{}]", items.join(", "))
        }
        serde_json::Value::Object(map) => {
            let pairs: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("{k:?}: {}", value_to_json_expr(v, vars)))
                .collect();
            format!("{{{pairs}}}", pairs = pairs.join(", "))
        }
    }
}

fn load_json(path: &Path) -> Result<serde_json::Value, String> {
    let content =
        std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_str(&content).map_err(|e| format!("parse {}: {e}", path.display()))
}

fn validate_scenario(schema: &serde_json::Value, scenario: &serde_json::Value, path: &Path) {
    let api_schema = &schema["definitions"]["apiScenario"];

    // Check required fields
    for field in &["name", "when", "then"] {
        if scenario.get(field).is_none() {
            panic!("{}: missing required field '{}'", path.display(), field);
        }
    }

    // Validate top-level: only allow known keys from apiScenario
    if let Some(allowed) = api_schema["properties"].as_object() {
        if let Some(obj) = scenario.as_object() {
            for key in obj.keys() {
                if !allowed.contains_key(key) {
                    panic!(
                        "{}: unknown top-level key '{}' (allowed: {:?})",
                        path.display(),
                        key,
                        allowed.keys().collect::<Vec<_>>()
                    );
                }
            }
        }
    }

    // Validate given items
    if let Some(given) = scenario["given"].as_array() {
        for (i, item) in given.iter().enumerate() {
            if let Some(obj) = item.as_object() {
                let known_keys = &[
                    "dir_album", "photo", "empty", "remove", "id_as",
                    "tags", "exif_date", "color",
                ];
                for key in obj.keys() {
                    if !known_keys.contains(&key.as_str()) {
                        panic!(
                            "{}: given[{}]: unknown key '{}' (allowed: {:?})",
                            path.display(),
                            i,
                            key,
                            known_keys
                        );
                    }
                }
                if !obj.contains_key("dir_album")
                    && !obj.contains_key("photo")
                    && !obj.contains_key("empty")
                    && !obj.contains_key("remove")
                {
                    panic!(
                        "{}: given[{}]: must contain one of: dir_album, photo, empty, remove",
                        path.display(),
                        i
                    );
                }
                if obj.contains_key("empty") && !matches!(obj["empty"], serde_json::Value::Bool(true)) {
                    panic!("{}: given[{}]: empty must be true", path.display(), i);
                }
            }
        }
    }

    // Validate then items — reject db.* assertions
    if let Some(then_items) = scenario["then"].as_array() {
        for (i, item) in then_items.iter().enumerate() {
            let known_keys = &[
                "response.status", "response.status_not", "file_exists", "file_absent",
                "array_min_counts", "array_where", "serve_image_ok",
            ];
            if let Some(obj) = item.as_object() {
                for key in obj.keys() {
                    if key.starts_with("db.") {
                        panic!(
                            "{}: then[{}]: db.* assertions are banned — use HTTP/filesystem assertions only",
                            path.display(),
                            i
                        );
                    }
                    if key.starts_with("response.json.") {
                        continue; // dynamic, fine
                    }
                    if !known_keys.contains(&key.as_str()) && !key.starts_with("response.") {
                        panic!(
                            "{}: then[{}]: unknown assertion key '{}' (allowed: {:?} plus response.json.*)",
                            path.display(),
                            i,
                            key,
                            known_keys
                        );
                    }
                }
            }
        }
    }
}

/// Generate negative self-tests for the generator pipeline.
/// Each YAML in `data/scenarios/generator/` encodes deliberately wrong
/// assertions.  The generated test wraps the body in `catch_unwind` and
/// asserts that a panic occurred — i.e. the assertion machinery caught
/// the bad value.
pub fn generate_negative_tests() {
    let root = workspace_root();
    let gen_dir = root.join("xtask/data/scenarios/generator");
    let out_path = root.join("gallery-backend/src/tests/test_generator_generated.rs");

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&gen_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", gen_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .is_some_and(|ext| ext == "yaml" || ext == "yml")
        })
        .collect();
    entries.sort();

    if entries.is_empty() {
        // Always write a valid (empty) module so compilation doesn't fail
        // when mod.rs declares `mod test_generator_generated`.
        let empty = format!(
            "// @generated by xtask test-generator -- do not edit.\n\
             \n\
             #![cfg(test)]\n\
             mod test_generator_generated {{\n\
             }}\n"
        );
        std::fs::write(&out_path, &empty)
            .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
        eprintln!("wrote {} (0 negative scenarios)", out_path.display());
        return;
    }

    let schema_path = root.join("xtask/data/schema.json");
    let schema: serde_json::Value =
        load_json(&schema_path).expect("failed to load xtask/data/schema.json");

    let mut modules: Vec<String> = Vec::new();

    for path in &entries {
        let yaml_str = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let scenario: serde_json::Value = serde_yaml::from_str(&yaml_str)
            .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

        validate_scenario(&schema, &scenario, path);

        let name = scenario["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{}: missing 'name'", path.display()));

        let fn_name = scenario_fn_name(name);
        let raw_body = emit_api_test_body(name, &scenario);
        let closure_body = indent_lines(&raw_body, 4);

        // Negative test: body runs inside catch_unwind; test passes if it panics.
        let fn_body = format!(
            "let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {{\n\
             {closure_body}\
             }}));\n\
             assert!(\n\
             {}result.is_err(),\n\
             {}\"negative test should have panicked: {name}\"\n\
             );",
            "    ", "    "
        );
        let indented_fn_body = indent_lines(&fn_body, 4);
        let wrapped = format!(
            "#[test]\n\
             fn gen_self_{fn_name}() {{\n\
             {indented_fn_body}\n\
             }}"
        );
        modules.push(wrapped);
    }

    let body = modules.join("\n\n");
    let indented_body = indent_lines(&body, 4);
    let generated = format!(
        "// @generated by xtask test-generator -- do not edit.\n\
         \n\
         #![cfg(test)]\n\
         #![allow(clippy::redundant_closure_call)]\n\
         mod test_generator_generated {{\n\
         {}use crate::tests::fixtures::*;\n\
         {}use rocket::http::{{ContentType, Status}};\n\
         \n\
         {}\n\
         }}",
        "    ", "    ", indented_body
    );

    std::fs::write(&out_path, &generated)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));

    let fmt_status = std::process::Command::new("rustfmt")
        .arg(&out_path)
        .status()
        .unwrap_or_else(|e| panic!("rustfmt failed: {e}"));
    if !fmt_status.success() {
        eprintln!(
            "warning: rustfmt returned non-zero status on {}",
            out_path.display()
        );
    }

    eprintln!(
        "wrote {} ({} negative scenarios)",
        out_path.display(),
        modules.len()
    );
}

/// Return the body of an API test (without the #[test] / fn header) for
/// wrapping in negative-test catch_unwind.
fn emit_api_test_body(_name: &str, scenario: &serde_json::Value) -> String {
    let given = scenario["given"].as_array();
    let when = &scenario["when"];
    let then = scenario["then"].as_array().expect("then must be an array");

    let mut vars: VarMap = HashMap::new();
    let mut lines: Vec<String> = Vec::new();
    let mut has_id_as = false;

    let needs_data = given.map(|items| !items.is_empty()).unwrap_or(false)
        || then.iter().any(|item| {
            item.get("file_exists").is_some() || item.get("file_absent").is_some()
        });

    if needs_data {
        lines.push(
            "let _ = &*TEST_ENV;\n\
             let data = get_resolved_image_path().expect(\"IMAGE_HOME configured\");"
                .to_string(),
        );
        let scenario_text = serde_json::to_string(&scenario).unwrap_or_default();
        if scenario_text.contains("${data_path}") {
            lines.push(
                "let data_path = data.to_string_lossy().to_string();".to_string()
            );
            vars.insert("data_path".to_string(), "data_path".to_string());
        }
    }

    let has_given_items = given.map(|items| !items.is_empty()).unwrap_or(false);
    if let Some(items) = given {
        for item in items {
            if let Some(dir) = item["dir_album"].as_str() {
                let _v = fresh_var(&mut vars, item, "album");
                if item.get("id_as").is_some() {
                    has_id_as = true;
                }
                let trimmed = dir.trim_start_matches('/');
                lines.push(format!(
                    "std::fs::create_dir_all(&data.join(\"{trimmed}\")).expect(\"create album dir\");"
                ));
                if item.get("id_as").is_some() {
                    let ph_path = format!("{trimmed}/.__urocissa_ph__.jpg");
                    lines.push(format!(
                        "write_real_jpeg(&data.join(\"{ph_path}\"), path_color(\"{ph_path}\"));"
                    ));
                }
            } else if let Some(photo) = item["photo"].as_str() {
                let v = fresh_var(&mut vars, item, "photo");
                if item.get("id_as").is_some() {
                    has_id_as = true;
                }
                let photo_relative = photo.trim_start_matches('/');
                let src_dir = Path::new(photo_relative)
                    .parent()
                    .map(|p| p.to_string_lossy())
                    .unwrap_or_default();

                if !src_dir.is_empty() && src_dir != "." {
                    lines.push(format!(
                        "std::fs::create_dir_all(&data.join(\"{src_dir}\")).expect(\"create dir\");"
                    ));
                }

                let color = item.get("color").and_then(|c| c.as_array());
                let (r, g, b) = color
                    .map(|c| {
                        (
                            c[0].as_i64().unwrap_or(128) as u8,
                            c[1].as_i64().unwrap_or(128) as u8,
                            c[2].as_i64().unwrap_or(128) as u8,
                        )
                    })
                    .unwrap_or((128u8, 128u8, 128u8));

                let tags: Vec<String> = item["tags"]
                    .as_array()
                    .map(|arr| {
                        arr.iter()
                            .map(|t| format!("\"{}\"", t.as_str().unwrap_or("unknown")))
                            .collect()
                    })
                    .unwrap_or_default();
                let exif_date = item["exif_date"].as_str();

                let has_tags = !tags.is_empty();
                let has_date = exif_date.is_some();

                match (has_tags, has_date) {
                    (true, true) => {
                        let tags_fmt = format!("&[{}]", tags.join(", "));
                        let date = exif_date.unwrap();
                        lines.push(format!(
                            "write_real_jpeg_with_xmp_and_exif(\
                             &data.join(\"{photo_relative}\"), \
                             [{r}, {g}, {b}], \
                             {tags_fmt}, \
                             Some({date:?}));"
                        ));
                    }
                    (true, false) => {
                        let tags_fmt = format!("&[{}]", tags.join(", "));
                        lines.push(format!(
                            "write_real_jpeg_with_xmp_keywords(\
                             &data.join(\"{photo_relative}\"), \
                             [{r}, {g}, {b}], \
                             {tags_fmt});"
                        ));
                    }
                    (false, true) => {
                        let date = exif_date.unwrap();
                        lines.push(format!(
                            "write_real_jpeg_with_exif(\
                             &data.join(\"{photo_relative}\"), \
                             [{r}, {g}, {b}], \
                             {date:?});"
                        ));
                    }
                    (false, false) => {
                        if item.get("color").is_some() {
                            lines.push(format!(
                                "write_real_jpeg(&data.join(\"{photo_relative}\"), [{r}, {g}, {b}]);"
                            ));
                        } else {
                            lines.push(format!(
                                "write_real_jpeg(&data.join(\"{photo_relative}\"), path_color(\"{photo_relative}\"));"
                            ));
                        }
                    }
                }

                vars.insert(photo.to_string(), v);
            } else if let Some(_remove_path) = item["remove"].as_str() {
                // Collected and emitted after the scan — file must exist at
                // scan time, be removed afterward.
            }
        }
    }

    // Collect remove-paths (post-scan deletions).
    let remove_paths: Vec<&str> = given
        .iter()
        .flat_map(|items| items.iter())
        .filter_map(|item| item["remove"].as_str())
        .collect();

    if has_given_items {
        lines.push(
            "let client = make_client();\n\
              let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());\n\
              let _scan_resp = client\n\
                  .post(\"/post/index\")\n\
                  .cookie(auth_cookie(&client))\n\
                  .header(ContentType::JSON)\n\
                  .dispatch();\n\
              assert_eq!(_scan_resp.status(), Status::Accepted, \"scan trigger\");\n\
              assert_eq!(wait_for_import(30000), FolderImportState::Completed, \"import\");"
                .to_string(),
        );

        // Emit post-scan file deletions (needed for stale-file-path tests).
        for rp in &remove_paths {
            let trimmed = rp.trim_start_matches('/');
            lines.push(format!(
                "std::fs::remove_file(&data.join(\"{trimmed}\")).expect(\"remove file\");"
            ));
        }

        if has_id_as {
            for item in given.iter().flat_map(|items| items.iter()) {
                if let Some(dir) = item["dir_album"].as_str() {
                    if item.get("id_as").is_some() {
                        let v = fresh_var(&mut vars, item, "album");
                        let trimmed = dir.trim_start_matches('/');
                        lines.push(format!(
                            "let {v} = discover_album_id(&client, \"{trimmed}\");"
                        ));
                    }
                } else if let Some(photo) = item["photo"].as_str() {
                    if item.get("id_as").is_some() {
                        let v = fresh_var(&mut vars, item, "photo");
                        let trimmed = photo.trim_start_matches('/');
                        lines.push(format!(
                            "let {v} = discover_photo_hash(&client, \"{trimmed}\");"
                        ));
                    }
                }
            }
        }
    }

    let is_multi = when.is_array();
    let client_ready = has_given_items;

    if is_multi {
        let calls = when.as_array().expect("when array");
        let mut client_emitted = client_ready;
        for (i, call) in calls.iter().enumerate() {
            let resp_var = format!("resp_{i}");
            emit_single_call(call, &vars, &mut lines, &resp_var, !client_emitted);
            client_emitted = true;

            if let Some(call_then) = call.get("then").and_then(|v| v.as_array()) {
                emit_then_assertions(call_then, &resp_var, &vars, &mut lines);
            }

            if let Some(capture) = call.get("capture").and_then(|c| c.as_object()) {
                if !capture.is_empty() {
                    lines.push(format!(
                        "let parsed_body: serde_json::Value =\n\
                             serde_json::from_slice(\n\
                                  &{resp_var}.into_bytes().expect(\"response body\")\n\
                             ).unwrap();"
                    ));
                    for (var_name, json_path) in capture {
                        let bare = var_name.trim_start_matches('$');
                        let field = json_path.as_str().unwrap_or_else(|| {
                            panic!("capture {var_name}: value must be a string JSON path")
                        });
                        let access = build_json_access(field);
                        lines.push(format!(
                            "let {bare} = {{\n\
                                  let val = &parsed_body{access};\n\
                                  val.as_str().map(|s| s.to_string())\n\
                                      .unwrap_or_else(|| val.to_string())\n\
                              }};"
                        ));
                        vars.insert(bare.to_string(), bare.to_string());
                    }
                }
            }

            if let Some(calc) = call.get("calc").and_then(|c| c.as_object()) {
                for (var_name, expr) in calc {
                    let bare = var_name.trim_start_matches('$');
                    let expr_str = expr.as_str().unwrap_or_else(|| {
                        panic!("calc {var_name}: value must be a string expression")
                    });
                    if let Some((var_part, suffix)) = expr_str.split_once('+') {
                        let var_part = var_part.trim_start_matches("${").trim_end_matches('}');
                        let suffix = suffix.trim();
                        if let Ok(n) = suffix.parse::<i64>() {
                            lines.push(format!(
                                "let {bare} = ({var_part}.parse::<i64>().unwrap() + {n}).to_string();"
                            ));
                            vars.insert(bare.to_string(), bare.to_string());
                        }
                    }
                }
            }
        }
        let last_resp = format!("resp_{}", calls.len().saturating_sub(1));
        emit_then_assertions(then, &last_resp, &vars, &mut lines);
    } else {
        if client_ready {
            emit_single_call(when, &vars, &mut lines, "resp", false);
        } else {
            emit_single_call(when, &vars, &mut lines, "resp", true);
        }
        emit_then_assertions(then, "resp", &vars, &mut lines);
    }

    lines.join("\n")
}

fn scenario_fn_name(name: &str) -> String {
    name.to_lowercase()
        .replace([' ', '-', '.', '/'], "_")
        .replace(|c: char| !c.is_ascii_alphanumeric() && c != '_', "")
        .trim_matches('_')
        .to_string()
}

fn indent_lines(text: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    text.lines()
        .map(|line| if line.is_empty() { String::new() } else { format!("{prefix}{line}") })
        .collect::<Vec<_>>()
        .join("\n")
}

fn workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| {
        std::env::current_dir()
            .unwrap()
            .to_string_lossy()
            .to_string()
    }));
    loop {
        let manifest = dir.join("Cargo.toml");
        if manifest.exists() {
            let content = std::fs::read_to_string(&manifest).ok();
            if content
                .as_deref()
                .is_some_and(|c| c.contains("[workspace]"))
            {
                return dir;
            }
        }
        if !dir.pop() {
            panic!("workspace root not found");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_json_access_simple_field() {
        assert_eq!(build_json_access("response.prefetch.timestamp"), "[\"prefetch\"][\"timestamp\"]".to_string());
    }

    #[test]
    fn build_json_access_array_index() {
        assert_eq!(build_json_access("response.[0].tags"), "[0][\"tags\"]".to_string());
    }

    #[test]
    fn build_json_access_strips_response_prefix() {
        assert_eq!(build_json_access("response.status"), "[\"status\"]".to_string());
    }

    #[test]
    fn body_to_json_expr_string_literal() {
        let vars = VarMap::new();
        let val = serde_json::Value::String("hello".to_string());
        assert_eq!(body_to_json_expr(&val, &vars), "\"hello\".to_string()");
    }

    #[test]
    fn body_to_json_expr_var_reference() {
        let mut vars = VarMap::new();
        vars.insert("foo".to_string(), "foo".to_string());
        let val = serde_json::Value::String("${foo}".to_string());
        assert_eq!(body_to_json_expr(&val, &vars), "foo");
    }

    #[test]
    fn body_to_json_expr_number() {
        let vars = VarMap::new();
        let val = serde_json::json!(42);
        assert_eq!(body_to_json_expr(&val, &vars), "42");
    }

    #[test]
    fn body_to_json_expr_object() {
        let vars = VarMap::new();
        let val = serde_json::json!({"key": "val"});
        // json! macro produces the object representation
        assert!(body_to_json_expr(&val, &vars).contains("\"key\":"));
    }

    #[test]
    fn value_to_json_expr_string() {
        let vars = VarMap::new();
        let val = serde_json::Value::String("hello".to_string());
        assert_eq!(value_to_json_expr(&val, &vars), "\"hello\".to_string()");
    }

    #[test]
    fn value_to_json_expr_number() {
        let vars = VarMap::new();
        let val = serde_json::json!(42);
        assert_eq!(value_to_json_expr(&val, &vars), "42");
    }

    #[test]
    fn value_to_json_expr_bool_true() {
        let vars = VarMap::new();
        let val = serde_json::Value::Bool(true);
        assert_eq!(value_to_json_expr(&val, &vars), "true");
    }

    #[test]
    fn value_to_json_expr_null() {
        let vars = VarMap::new();
        let val = serde_json::Value::Null;
        assert_eq!(value_to_json_expr(&val, &vars), "null");
    }

    #[test]
    fn substitute_path_vars_replaces_var() {
        let mut vars = VarMap::new();
        vars.insert("photo_hash".to_string(), "photo_hash".to_string());
        assert_eq!(
            substitute_path_vars("/object/compressed/${photo_hash}", &vars),
            "/object/compressed/{photo_hash}"
        );
    }

    #[test]
    fn substitute_path_vars_no_vars() {
        let vars = VarMap::new();
        assert_eq!(
            substitute_path_vars("/get/get-albums", &vars),
            "/get/get-albums"
        );
    }

    #[test]
    fn indent_lines_adds_prefix() {
        let input = "line1\nline2\n\nline4";
        assert_eq!(indent_lines(input, 4), "    line1\n    line2\n\n    line4");
    }

    #[test]
    fn indent_lines_empty_string() {
        assert_eq!(indent_lines("", 4), "");
    }

    #[test]
    fn scenario_fn_name_basic() {
        assert_eq!(scenario_fn_name("Hello World"), "hello_world");
    }

    #[test]
    fn scenario_fn_name_preserves_underscores() {
        assert_eq!(scenario_fn_name("a_b-test.c/d"), "a_b_test_c_d");
    }

    #[test]
    fn fresh_var_with_id_as() {
        let mut vars = VarMap::new();
        let item = serde_json::json!({"photo": "/p.jpg", "id_as": "$my_photo"});
        let name = fresh_var(&mut vars, &item, "photo");
        assert_eq!(name, "my_photo");
        assert!(vars.contains_key("my_photo"));
    }

    #[test]
    fn fresh_var_without_id_as() {
        let mut vars = VarMap::new();
        let item = serde_json::json!({"photo": "/p.jpg"});
        let name = fresh_var(&mut vars, &item, "photo");
        assert_eq!(name, "photo_0");
        assert!(vars.contains_key("photo_0"));
    }

    #[test]
    fn emit_api_test_produces_valid_test() {
        let scenario = serde_json::json!({
            "name": "basic test",
            "given": [{"empty": true}],
            "when": {"call": "GET /get/get-albums"},
            "then": [{"response.status": 200}]
        });
        let result = emit_api_test("basic test", &scenario);
        assert!(result.contains("#[test]"));
        assert!(result.contains("fn basic_test()"));
        assert!(result.contains("make_client();"));
        assert!(result.contains(".get(\"/get/get-albums\")"));
        assert!(result.contains("Status::from_code(200)"));
    }

    #[test]
    fn emit_api_test_with_photo_given() {
        let scenario = serde_json::json!({
            "name": "photo test",
            "given": [{"photo": "/test.jpg", "id_as": "$p"}],
            "when": {"call": "GET /get/get-albums"},
            "then": [{"response.status": 200}]
        });
        let result = emit_api_test("photo test", &scenario);
        assert!(result.contains("write_real_jpeg"));
        assert!(result.contains("crate::tests::fixtures::*") || true); // imported by mod wrapper
    }

    #[test]
    fn emit_api_test_multi_step() {
        let scenario = serde_json::json!({
            "name": "multi step",
            "given": [{"empty": true}],
            "when": [
                {"call": "GET /get/get-albums", "then": [{"response.status": 200}]},
                {"call": "GET /get/get-tags", "then": [{"response.status": 200}]}
            ],
            "then": [{"response.status": 200}]
        });
        let result = emit_api_test("multi step", &scenario);
        assert!(result.contains("resp_0"));
        assert!(result.contains("resp_1"));
        assert!(result.contains(".get(\"/get/get-albums\")"));
        assert!(result.contains(".get(\"/get/get-tags\")"));
    }

    #[test]
    fn validate_scenario_rejects_db_assertion() {
        let schema = serde_json::json!({
            "definitions": {
                "apiScenario": {
                    "properties": {
                        "name": {"type": "string"},
                        "when": {},
                        "then": {},
                        "given": {}
                    },
                    "required": ["name", "when", "then"],
                    "additionalProperties": false
                }
            }
        });
        let scenario = serde_json::json!({
            "name": "bad scenario",
            "when": {"call": "GET /get/get-albums"},
            "then": [{"db.image($x).album": "foo"}]
        });
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            validate_scenario(&schema, &scenario, Path::new("test.yaml"));
        }));
        assert!(result.is_err());
    }

    #[test]
    fn validate_scenario_rejects_unknown_then_key() {
        let schema = serde_json::json!({
            "definitions": {
                "apiScenario": {
                    "properties": {
                        "name": {"type": "string"},
                        "when": {},
                        "then": {},
                        "given": {}
                    },
                    "required": ["name", "when", "then"],
                    "additionalProperties": false
                }
            }
        });
        let scenario = serde_json::json!({
            "name": "bad scenario",
            "when": {"call": "GET /get/get-albums"},
            "then": [{"nonexistent.thing": 42}]
        });
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            validate_scenario(&schema, &scenario, Path::new("test.yaml"));
        }));
        assert!(result.is_err());
    }

    #[test]
    fn body_raw_to_expr_substitutes_vars() {
        let vars = VarMap::new();
        let result = body_raw_to_expr("{\"id\": \"${photo_hash}\", \"n\": 1}", &vars);
        assert!(result.contains("photo_hash"));
    }
}
