use std::collections::HashMap;
use std::path::{Path, PathBuf};

type VarMap = HashMap<String, String>;

pub fn generate_all() {
    let root = workspace_root();
    let api_dir = root.join("scenarios/api");
    let schema_path = root.join("scenarios/schema.json");
    let openapi_path = root.join("gallery-backend/openapi.json");
    let out_path = root.join("gallery-backend/src/tests/scenarios_generated.rs");

    let _schema: serde_json::Value =
        load_json(&schema_path).expect("failed to load scenarios/schema.json");
    let _openapi: serde_json::Value =
        load_json(&openapi_path).expect("failed to load gallery-backend/openapi.json");

    let mut modules: Vec<String> = Vec::new();

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&api_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", api_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .is_some_and(|ext| ext == "yaml" || ext == "yml")
        })
        .collect();
    entries.sort();

    for path in &entries {
        let yaml_str = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let scenario: serde_json::Value = serde_yaml::from_str(&yaml_str)
            .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));

        let name = scenario["name"]
            .as_str()
            .unwrap_or_else(|| panic!("{}: missing 'name'", path.display()));

        let test_fn = emit_api_test(name, &scenario);
        modules.push(test_fn);
    }

    let body = modules.join("\n\n");
    let generated = format!(
        "// @generated by xtask gen-scenarios -- do not edit.\n\
         // Re-generate with: cargo xtask gen-scenarios\n\
         \n\
         #![cfg(test)]\n\
         #![allow(clippy::module_inception, clippy::needless_borrows_for_generic_args)]\n\
         mod scenarios_generated {{\n\
             use crate::tests::fixtures::*;\n\
             use rocket::http::{{ContentType, Status}};\n\
         \n\
         {body}\n\
         }}\n"
    );

    std::fs::write(&out_path, &generated)
        .unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));

    // Post-process with rustfmt to ensure consistent formatting.
    let fmt_status = std::process::Command::new("rustfmt")
        .arg(&out_path)
        .status()
        .unwrap_or_else(|e| panic!("rustfmt failed: {e}"));
    if !fmt_status.success() {
        eprintln!(
            "warning: rustfmt returned non-zero status on {}",
            out_path.display()
        );
    }

    eprintln!("wrote {} ({} scenarios)", out_path.display(), modules.len());
}

fn emit_api_test(name: &str, scenario: &serde_json::Value) -> String {
    let fn_name = name
        .to_lowercase()
        .replace([' ', '-', '.', '/'], "_")
        .replace(|c: char| !c.is_ascii_alphanumeric() && c != '_', "")
        .trim_matches('_')
        .to_string();

    let given = scenario["given"].as_array();
    let when = &scenario["when"];
    let then = scenario["then"].as_array().expect("then must be an array");

    let mut vars: VarMap = HashMap::new();
    let mut lines: Vec<String> = Vec::new();

    // Check whether we need DATA_PATH (given items or file/DB assertions)
    let needs_data = given.map(|items| !items.is_empty()).unwrap_or(false)
        || then.iter().any(|item| {
            item.get("file_exists").is_some()
                || item.get("file_absent").is_some()
                || item.as_object().is_some_and(|m| {
                    m.keys()
                        .any(|k| k.starts_with("db.image(") || k.starts_with("db.album("))
                })
        });

    if needs_data {
        lines.push(
            "let data = {\n\
                 let _ = &*TEST_ENV;\n\
                 DATA_PATH.get().expect(\"DATA_PATH initialised\")\n\
             };"
            .to_string(),
        );
    }

    // Process given items
    if let Some(items) = given {
        for item in items {
            if let Some(dir) = item["dir_album"].as_str() {
                let v = fresh_var(&mut vars, item, "album");
                let trimmed = dir.trim_start_matches('/');
                lines.push(format!(
                    "std::fs::create_dir_all(&data.join(\"{trimmed}\")).expect(\"create album dir\");"
                ));
                lines.push(format!(
                    "let {v} = make_dir_album(&data.join(\"{trimmed}\"));"
                ));
            } else if let Some(photo) = item["photo"].as_str() {
                let v = fresh_var(&mut vars, item, "photo");
                let photo_relative = photo.trim_start_matches('/');
                let src_dir = Path::new(photo_relative)
                    .parent()
                    .map(|p| p.to_string_lossy())
                    .unwrap_or_default();

                if !src_dir.is_empty() && src_dir != "." {
                    lines.push(format!(
                        "std::fs::create_dir_all(&data.join(\"{src_dir}\")).expect(\"create dir\");"
                    ));
                }

                let has_color = item.get("color").and_then(|c| c.as_array()).is_some();

                if has_color {
                    let color = item["color"].as_array().unwrap();
                    let r = color[0].as_i64().unwrap_or(128);
                    let g = color[1].as_i64().unwrap_or(128);
                    let b = color[2].as_i64().unwrap_or(128);
                    lines.push(format!(
                        "write_real_jpeg(&data.join(\"{photo_relative}\"), [{r}, {g}, {b}]);"
                    ));
                } else {
                    lines.push(format!(
                        "std::fs::write(&data.join(\"{photo_relative}\"), b\"\\xff\\xd8\\xff fake jpeg\").expect(\"write source file\");"
                    ));
                }

                let tags: Vec<String> = item["tags"]
                    .as_array()
                    .map(|arr| {
                        arr.iter()
                            .map(|t| format!("\"{}\"", t.as_str().unwrap_or("unknown")))
                            .collect()
                    })
                    .unwrap_or_default();
                let tags_arr = if tags.is_empty() {
                    "&[]".to_string()
                } else {
                    format!("&[{}]", tags.join(", "))
                };
                let exif_date = item["exif_date"]
                    .as_str()
                    .map(|d| format!("Some({d:?})"))
                    .unwrap_or_else(|| "None".to_string());

                lines.push(format!(
                    "let {v} = {{\n\
                         let src = data.join(\"{photo_relative}\");\n\
                         insert_photos(&[PhotoSpec {{ path: src.to_str().unwrap(), tags: {tags_arr}, exif_date: {exif_date} }}]);\n\
                         find_hash_by_alias_path(&src)\n\
                     }};"
                ));

                vars.insert(photo.to_string(), v);
            }
        }
    }

    // Process when block
    let call = when["call"].as_str().expect("when.call is required");
    let body_val = when.get("body");
    let auth = when.get("auth").and_then(|v| v.as_bool()).unwrap_or(true);

    let parts: Vec<&str> = call.splitn(2, ' ').collect();
    let method = parts[0];
    let path = parts[1];

    let body_str = body_val
        .map(|b| body_to_json_expr(b, &vars))
        .unwrap_or_default();

    if auth {
        lines.push("let client = make_client();".to_string());
        lines.push("let cookie = auth_cookie(&client);".to_string());
    } else {
        lines.push("let client = make_client();".to_string());
    }

    let method_lower = method.to_lowercase();
    let mut req = format!("let resp = client\n    .{method_lower}(\"{path}\")");
    if auth {
        req.push_str("\n    .cookie(cookie)");
    }
    if !body_str.is_empty() && method != "GET" {
        req.push_str("\n    .header(ContentType::JSON)");
        req.push_str(&format!("\n    .body({body_str})"));
    }
    req.push_str("\n    .dispatch();");
    lines.push(req);

    // Process then assertions
    for item in then {
        if let Some(code) = item["response.status"].as_i64() {
            lines.push(format!(
                "assert_eq!(resp.status(), Status::from_code({code}).unwrap(), \"{path} failed\");"
            ));
        } else if let Some(code) = item["response.status_not"].as_i64() {
            lines.push(format!(
                "assert_ne!(resp.status(), Status::from_code({code}).unwrap(), \"{path} must not return {code}\");"
            ));
        } else if let Some(file_path) = item["file_exists"].as_str() {
            let trimmed = file_path.trim_start_matches('/');
            lines.push(format!(
                "assert!(data.join(\"{trimmed}\").exists(), \"file should exist: {trimmed}\");"
            ));
        } else if let Some(file_path) = item["file_absent"].as_str() {
            let trimmed = file_path.trim_start_matches('/');
            lines.push(format!(
                "assert!(!data.join(\"{trimmed}\").exists(), \"file should be absent: {trimmed}\");"
            ));
        } else if let Some((key, val)) = item.as_object().and_then(|m| m.iter().next())
            && (key.starts_with("db.image(") || key.starts_with("db.album("))
        {
            let inner = key
                .strip_prefix("db.image(")
                .or_else(|| key.strip_prefix("db.album("))
                .expect("db assertion key");
            let (id_expr, field_path) = inner.split_once(')').expect("db assertion syntax");
            let field_path = field_path.strip_prefix('.').unwrap_or(field_path);
            let field_path = if field_path.starts_with("metadata.") {
                field_path.to_string()
            } else {
                format!("metadata.{field_path}")
            };

            let (db_id, db_is_var) = if id_expr.starts_with('$') {
                let bare = id_expr.trim_start_matches('$');
                let val = vars
                    .get(bare)
                    .cloned()
                    .unwrap_or_else(|| panic!("unknown variable {id_expr}"));
                (val, true)
            } else {
                (id_expr.to_string(), false)
            };

            let db_id_for_get = if db_is_var {
                db_id.clone()
            } else {
                format!("{db_id:?}")
            };

            let db_type = if key.starts_with("db.image(") {
                "Image"
            } else {
                "Album"
            };

            lines.push(format!(
                "{{\n\
                     let txn = TREE.in_disk.begin_read().expect(\"begin read\");\n\
                     let table = txn.open_table(DATA_TABLE).expect(\"open table\");\n\
                      let guard = table\n\
                          .get({db_id_for_get}.as_str())\n\
                         .expect(\"redb get\")\n\
                         .expect(\"record in redb\");\n\
                     let AbstractData::{db_type}(record) = guard.value() else {{\n\
                         panic!(\"not a {db_type} record\");\n\
                     }};\n\
                     assert_eq!(\n\
                         format!(\"{{:?}}\", record.{field_path}),\n\
                         format!(\"{{:?}}\", {expect}),\n\
                         \"{key} mismatch\"\n\
                     );\n\
                 }}",
                expect = json_value_to_rust(val)
            ));
        }
    }

    let body = lines.join("\n    ");
    format!(
        "#[test]\n\
         fn {fn_name}() {{\n\
             {body}\n\
         }}"
    )
}

fn fresh_var(vars: &mut VarMap, item: &serde_json::Value, prefix: &str) -> String {
    if let Some(id) = item["id_as"].as_str() {
        let bare = id.trim_start_matches('$');
        let code_name = bare.to_string();
        vars.entry(bare.to_string())
            .or_insert_with(|| code_name.clone());
        code_name
    } else {
        let idx = vars.len();
        let name = format!("{prefix}_{idx}");
        vars.insert(name.clone(), name.clone());
        name
    }
}

fn body_to_json_expr(val: &serde_json::Value, vars: &VarMap) -> String {
    match val {
        serde_json::Value::String(s) => {
            if let Some(bare) = s.strip_prefix("${").and_then(|s| s.strip_suffix('}')) {
                if let Some(rust_var) = vars.get(bare) {
                    rust_var.clone()
                } else {
                    format!("{bare:?}.to_string()")
                }
            } else {
                format!("{s:?}.to_string()")
            }
        }
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "serde_json::Value::Null".to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(|v| body_to_json_expr(v, vars)).collect();
            format!("vec![{}]", items.join(", "))
        }
        serde_json::Value::Object(map) => {
            let pairs: Vec<String> = map
                .iter()
                .map(|(k, v)| format!("{k:?}: {}", body_to_json_expr(v, vars)))
                .collect();
            format!("serde_json::json!({{{}}}).to_string()", pairs.join(", "))
        }
    }
}

fn json_value_to_rust(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => {
            // Path-like strings (starting with /) are data-relative.
            if s.starts_with('/') {
                let trimmed = s.trim_start_matches('/');
                format!("data.join({trimmed:?}).to_string_lossy().to_string()")
            } else {
                format!("{s:?}.to_string()")
            }
        }
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "None".to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(json_value_to_rust).collect();
            format!("vec![{}]", items.join(", "))
        }
        _ => "todo!()".to_string(),
    }
}

fn load_json(path: &Path) -> Result<serde_json::Value, String> {
    let content =
        std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_str(&content).map_err(|e| format!("parse {}: {e}", path.display()))
}

fn workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| {
        std::env::current_dir()
            .unwrap()
            .to_string_lossy()
            .to_string()
    }));
    loop {
        let manifest = dir.join("Cargo.toml");
        if manifest.exists() {
            let content = std::fs::read_to_string(&manifest).ok();
            if content
                .as_deref()
                .is_some_and(|c| c.contains("[workspace]"))
            {
                return dir;
            }
        }
        if !dir.pop() {
            panic!("workspace root not found");
        }
    }
}
