// @generated by xtask gen-scenarios -- do not edit.
// Re-generate with: cargo xtask gen-scenarios

#![cfg(test)]
#![allow(clippy::module_inception, clippy::needless_borrows_for_generic_args)]
mod scenarios_generated {
    use crate::tests::fixtures::*;
    use rocket::http::{ContentType, Status};

    #[test]
    fn assign_album_moves_file_and_updates_membership() {
        let data = {
            let _ = &*TEST_ENV;
            DATA_PATH.get().expect("DATA_PATH initialised")
        };
        std::fs::create_dir_all(&data.join("gen_e2e_h_album")).expect("create album dir");
        let album = make_dir_album(&data.join("gen_e2e_h_album"));
        std::fs::create_dir_all(&data.join("gen_e2e_h_import")).expect("create dir");
        std::fs::write(
            &data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg"),
            b"\xff\xd8\xff fake jpeg",
        )
        .expect("write source file");
        let photo = {
            let src = data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg");
            insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &[],
                exif_date: None,
            }]);
            find_hash_by_alias_path(&src)
        };
        let client = make_client();
        let cookie = auth_cookie(&client);
        let resp = client
            .put("/put/assign_album")
            .cookie(cookie)
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(200).unwrap(),
            "/put/assign_album failed"
        );
        assert!(
            data.join("gen_e2e_h_album/gen_e2e_h_photo.jpg").exists(),
            "file should exist: gen_e2e_h_album/gen_e2e_h_photo.jpg"
        );
        assert!(
            !data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg").exists(),
            "file should be absent: gen_e2e_h_import/gen_e2e_h_photo.jpg"
        );
        {
            let txn = TREE.in_disk.begin_read().expect("begin read");
            let table = txn.open_table(DATA_TABLE).expect("open table");
            let guard = table
                .get(photo.as_str())
                .expect("redb get")
                .expect("record in redb");
            let AbstractData::Image(record) = guard.value() else {
                panic!("not a Image record");
            };
            assert_eq!(
                format!("{:?}", record.metadata.alias[0].file),
                format!(
                    "{:?}",
                    data.join("gen_e2e_h_album/gen_e2e_h_photo.jpg")
                        .to_string_lossy()
                        .to_string()
                ),
                "db.image($photo).alias[0].file mismatch"
            );
        }
        {
            let txn = TREE.in_disk.begin_read().expect("begin read");
            let table = txn.open_table(DATA_TABLE).expect("open table");
            let guard = table
                .get(album.as_str())
                .expect("redb get")
                .expect("record in redb");
            let AbstractData::Album(record) = guard.value() else {
                panic!("not a Album record");
            };
            assert_eq!(
                format!("{:?}", record.metadata.item_count),
                format!("{:?}", 1),
                "db.album($album).item_count mismatch"
            );
        }
    }

    #[test]
    fn assign_album_endpoint_is_registered() {
        let client = make_client();
        let cookie = auth_cookie(&client);
        let resp = client
    .put("/put/assign_album")
    .cookie(cookie)
    .header(ContentType::JSON)
    .body(serde_json::json!({"albumId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb".to_string(), "hash": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string()}).to_string())
    .dispatch();
        assert_ne!(
            resp.status(),
            Status::from_code(404).unwrap(),
            "/put/assign_album must not return 404"
        );
    }

    #[test]
    fn create_empty_album_endpoint_removed() {
        let client = make_client();
        let cookie = auth_cookie(&client);
        let resp = client
            .post("/post/create_empty_album")
            .cookie(cookie)
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(404).unwrap(),
            "/post/create_empty_album failed"
        );
    }
}
