// @generated by xtask gen-scenarios -- do not edit.
// Re-generate with: cargo xtask gen-scenarios

#![cfg(test)]
#![allow(clippy::module_inception, clippy::needless_borrows_for_generic_args)]
mod scenarios_generated {
    use crate::tests::fixtures::*;
    use rocket::http::{ContentType, Status};

    #[test]
    fn album_membership_is_singular() {
        let data = {
            let _ = &*TEST_ENV;
            DATA_PATH.get().expect("DATA_PATH initialised")
        };
        std::fs::create_dir_all(&data.join("gen_e2e_i_album_a")).expect("create album dir");
        let album_a = make_dir_album(&data.join("gen_e2e_i_album_a"));
        std::fs::create_dir_all(&data.join("gen_e2e_i_album_b")).expect("create album dir");
        let album_b = make_dir_album(&data.join("gen_e2e_i_album_b"));
        std::fs::create_dir_all(&data.join("gen_e2e_i_import")).expect("create dir");
        std::fs::write(
            &data.join("gen_e2e_i_import/gen_e2e_i_photo.jpg"),
            b"\xff\xd8\xff fake jpeg",
        )
        .expect("write source file");
        let photo = {
            let src = data.join("gen_e2e_i_import/gen_e2e_i_photo.jpg");
            let hashes = insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &[],
                exif_date: None,
            }]);
            hashes[0].clone()
        };
        let client = make_client();
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album_a, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album_b, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
    }

    #[test]
    fn assign_album_moves_file_and_updates_membership() {
        let data = {
            let _ = &*TEST_ENV;
            DATA_PATH.get().expect("DATA_PATH initialised")
        };
        std::fs::create_dir_all(&data.join("gen_e2e_h_album")).expect("create album dir");
        let album = make_dir_album(&data.join("gen_e2e_h_album"));
        std::fs::create_dir_all(&data.join("gen_e2e_h_import")).expect("create dir");
        std::fs::write(
            &data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg"),
            b"\xff\xd8\xff fake jpeg",
        )
        .expect("write source file");
        let photo = {
            let src = data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg");
            let hashes = insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &[],
                exif_date: None,
            }]);
            hashes[0].clone()
        };
        let client = make_client();
        let resp = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(200).unwrap(),
            "call resp status"
        );
        assert!(
            data.join("gen_e2e_h_album/gen_e2e_h_photo.jpg").exists(),
            "file should exist: gen_e2e_h_album/gen_e2e_h_photo.jpg"
        );
        assert!(
            !data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg").exists(),
            "file should be absent: gen_e2e_h_import/gen_e2e_h_photo.jpg"
        );
    }

    #[test]
    fn assign_album_endpoint_is_registered() {
        let client = make_client();
        let resp = client
    .put("/put/assign_album")
    .cookie(auth_cookie(&client))
    .header(ContentType::JSON)
    .body(serde_json::json!({"albumId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb".to_string(), "hash": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string()}).to_string())
    .dispatch();
        assert_ne!(
            resp.status(),
            Status::from_code(404).unwrap(),
            "call resp must not return 404"
        );
    }

    #[test]
    fn create_empty_album_endpoint_removed() {
        let client = make_client();
        let resp = client
            .post("/post/create_empty_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(404).unwrap(),
            "call resp status"
        );
    }

    #[test]
    fn photo_tags_reflect_injected_metadata() {
        let data = {
            let _ = &*TEST_ENV;
            DATA_PATH.get().expect("DATA_PATH initialised")
        };
        std::fs::create_dir_all(&data.join("e2e_b/2023/summer")).expect("create dir");
        std::fs::write(
            &data.join("e2e_b/2023/summer/beach.jpg"),
            b"\xff\xd8\xff fake jpeg",
        )
        .expect("write source file");
        {
            let src = data.join("e2e_b/2023/summer/beach.jpg");
            insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &["e2e_b_nature", "e2e_b_summer", "e2e_b_beach"],
                exif_date: Some("2023:07:15 10:00:00"),
            }]);
        }
        std::fs::create_dir_all(&data.join("e2e_b/2023/summer")).expect("create dir");
        std::fs::write(
            &data.join("e2e_b/2023/summer/sunset.jpg"),
            b"\xff\xd8\xff fake jpeg",
        )
        .expect("write source file");
        {
            let src = data.join("e2e_b/2023/summer/sunset.jpg");
            insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &["e2e_b_nature", "e2e_b_summer"],
                exif_date: Some("2023:07:16 20:00:00"),
            }]);
        }
        std::fs::create_dir_all(&data.join("e2e_b/2024/winter")).expect("create dir");
        std::fs::write(
            &data.join("e2e_b/2024/winter/snow.jpg"),
            b"\xff\xd8\xff fake jpeg",
        )
        .expect("write source file");
        {
            let src = data.join("e2e_b/2024/winter/snow.jpg");
            insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &["e2e_b_nature", "e2e_b_winter"],
                exif_date: Some("2024:01:10 09:00:00"),
            }]);
        }
        std::fs::create_dir_all(&data.join("e2e_b/2024/city")).expect("create dir");
        std::fs::write(
            &data.join("e2e_b/2024/city/skyline.jpg"),
            b"\xff\xd8\xff fake jpeg",
        )
        .expect("write source file");
        {
            let src = data.join("e2e_b/2024/city/skyline.jpg");
            insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &["e2e_b_architecture", "e2e_b_city"],
                exif_date: None,
            }]);
        }
        let client = make_client();
        let resp_0 = client
            .get("/get/get-tags")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_0.into_bytes().expect("response body"))
                .expect("valid JSON");
        let tags = parsed_final.as_array().expect("response must be an array");
        for (tag, min) in [
            ("e2e_b_architecture", 1u64),
            ("e2e_b_beach", 1u64),
            ("e2e_b_city", 1u64),
            ("e2e_b_nature", 3u64),
            ("e2e_b_summer", 2u64),
            ("e2e_b_winter", 1u64),
        ] {
            let got = tags
                .iter()
                .find(|t| t["tag"].as_str() == Some(tag))
                .and_then(|t| t["number"].as_u64())
                .unwrap_or(0);
            assert!(got >= min, "tag '{tag}': expected >= {min}, got {got}");
        }
    }

    #[test]
    fn tags_visible_via_get_data() {
        let data = {
            let _ = &*TEST_ENV;
            DATA_PATH.get().expect("DATA_PATH initialised")
        };
        std::fs::create_dir_all(&data.join("e2e_o")).expect("create dir");
        std::fs::write(&data.join("e2e_o/tagged.jpg"), b"\xff\xd8\xff fake jpeg")
            .expect("write source file");
        let photo = {
            let src = data.join("e2e_o/tagged.jpg");
            let hashes = insert_photos(&[PhotoSpec {
                path: src.to_str().unwrap(),
                tags: &["e2e_o_family", "e2e_o_vacation"],
                exif_date: None,
            }]);
            hashes[0].clone()
        };
        let client = make_client();
        let resp_0 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_0.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_1 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_1.into_bytes().expect("response body"))
                .expect("valid JSON");
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_o_family".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_o_family"
        );
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_o_vacation".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_o_vacation"
        );
    }
}
