// @generated by cargo xtask test-backend -- do not edit.
// Re-generate with: cargo xtask test-backend

#![cfg(test)]
#![allow(clippy::module_inception, clippy::needless_borrows_for_generic_args)]
mod scenarios_generated {
    use crate::tests::bootstrap::*;
    use rocket::http::{ContentType, Status};
    use xtask::fixtures::*;

    #[test]
    fn album_membership_is_singular() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("gen_e2e_i_album_a")).expect("create album dir");
        write_real_jpeg(
            &data.join("gen_e2e_i_album_a/.__urocissa_ph__.jpg"),
            path_color("gen_e2e_i_album_a/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("gen_e2e_i_album_b")).expect("create album dir");
        write_real_jpeg(
            &data.join("gen_e2e_i_album_b/.__urocissa_ph__.jpg"),
            path_color("gen_e2e_i_album_b/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("gen_e2e_i_import")).expect("create dir");
        write_real_jpeg(
            &data.join("gen_e2e_i_import/gen_e2e_i_photo.jpg"),
            path_color("gen_e2e_i_import/gen_e2e_i_photo.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let album_a = discover_album_id(&client, "gen_e2e_i_album_a");
        let album_b = discover_album_id(&client, "gen_e2e_i_album_b");
        let photo = discover_photo_hash(&client, "gen_e2e_i_import/gen_e2e_i_photo.jpg");
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album_a, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album_b, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
    }

    #[test]
    fn album_visible_via_get_data_after_assign() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_q_album")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_q_album/.__urocissa_ph__.jpg"),
            path_color("e2e_q_album/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_q_import")).expect("create dir");
        write_real_jpeg(
            &data.join("e2e_q_import/e2e_q_photo.jpg"),
            path_color("e2e_q_import/e2e_q_photo.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let album = discover_album_id(&client, "e2e_q_album");
        let photo = discover_photo_hash(&client, "e2e_q_import/e2e_q_photo.jpg");
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_1.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_2 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_2.status(),
            Status::from_code(200).unwrap(),
            "call resp_2 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_2.into_bytes().expect("response body"))
                .expect("valid JSON");
        assert_eq!(
            parsed_final[0]["abstractData"]["album"],
            serde_json::json!(album),
            "response.json.[0].abstractData.album mismatch"
        );
    }

    #[test]
    fn assign_album_moves_file_and_updates_membership() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("gen_e2e_h_album")).expect("create album dir");
        write_real_jpeg(
            &data.join("gen_e2e_h_album/.__urocissa_ph__.jpg"),
            path_color("gen_e2e_h_album/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("gen_e2e_h_import")).expect("create dir");
        write_real_jpeg(
            &data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg"),
            path_color("gen_e2e_h_import/gen_e2e_h_photo.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let album = discover_album_id(&client, "gen_e2e_h_album");
        let photo = discover_photo_hash(&client, "gen_e2e_h_import/gen_e2e_h_photo.jpg");
        let resp = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(200).unwrap(),
            "call resp status"
        );
        assert!(
            data.join("gen_e2e_h_album/gen_e2e_h_photo.jpg").exists(),
            "file should exist: gen_e2e_h_album/gen_e2e_h_photo.jpg"
        );
        assert!(
            !data.join("gen_e2e_h_import/gen_e2e_h_photo.jpg").exists(),
            "file should be absent: gen_e2e_h_import/gen_e2e_h_photo.jpg"
        );
    }

    #[test]
    fn assign_album_endpoint_is_registered() {
        let client = make_client();
        let resp = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb".to_string(), "hash": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string()}).to_string())
            .dispatch();
        assert_ne!(
            resp.status(),
            Status::from_code(404).unwrap(),
            "call resp must not return 404"
        );
    }

    #[test]
    fn assign_album_rejects_manual_album() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("manual_album_test")).expect("create dir");
        write_real_jpeg(
            &data.join("manual_album_test/photo.jpg"),
            path_color("manual_album_test/photo.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let photo = discover_photo_hash(&client, "manual_album_test/photo.jpg");
        let resp = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(
                serde_json::json!({"albumId": "bogus-manual-album".to_string(), "hash": photo})
                    .to_string(),
            )
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(400).unwrap(),
            "call resp status"
        );
    }

    #[test]
    fn assign_album_rejects_stale_file_path() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_j/album")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_j/album/.__urocissa_ph__.jpg"),
            path_color("e2e_j/album/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_j")).expect("create dir");
        write_real_jpeg(&data.join("e2e_j/photo.jpg"), path_color("e2e_j/photo.jpg"));
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        std::fs::remove_file(&data.join("e2e_j/photo.jpg")).expect("remove file");
        let album = discover_album_id(&client, "e2e_j/album");
        let photo = discover_photo_hash(&client, "e2e_j/photo.jpg");
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_ne!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 must not return 200"
        );
    }

    #[test]
    fn complex_import_create_album_assign_and_verify_tags_and_files() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_w/parent")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_w/parent/.__urocissa_ph__.jpg"),
            path_color("e2e_w/parent/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_w")).expect("create dir");
        write_real_jpeg_with_xmp_keywords(
            &data.join("e2e_w/photo1.jpg"),
            [128, 128, 128],
            &["e2e_w_city", "e2e_w_travel"],
        );
        std::fs::create_dir_all(&data.join("e2e_w")).expect("create dir");
        write_real_jpeg_with_xmp_keywords(
            &data.join("e2e_w/photo2.jpg"),
            [128, 128, 128],
            &["e2e_w_city", "e2e_w_architecture"],
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let parent = discover_album_id(&client, "e2e_w/parent");
        let photo1 = discover_photo_hash(&client, "e2e_w/photo1.jpg");
        let photo2 = discover_photo_hash(&client, "e2e_w/photo2.jpg");
        let resp_0 = client
            .post("/post/create_dir_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(
                serde_json::json!({"name": "vacation".to_string(), "parentAlbumId": parent})
                    .to_string(),
            )
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": parent, "hash": photo1}).to_string())
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
        let resp_2 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": parent, "hash": photo2}).to_string())
            .dispatch();
        assert_eq!(
            resp_2.status(),
            Status::from_code(200).unwrap(),
            "call resp_2 status"
        );
        let resp_3 = client
            .get("/get/get-tags")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_3.status(),
            Status::from_code(200).unwrap(),
            "call resp_3 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_3.into_bytes().expect("response body"))
                .expect("valid JSON");
        let tags = parsed_final.as_array().expect("response must be an array");
        for (tag, min) in [
            ("e2e_w_architecture", 1u64),
            ("e2e_w_city", 2u64),
            ("e2e_w_travel", 1u64),
        ] {
            let got = tags
                .iter()
                .find(|t| t["tag"].as_str() == Some(tag))
                .and_then(|t| t["number"].as_u64())
                .unwrap_or(0);
            assert!(got >= min, "tag '{tag}': expected >= {min}, got {got}");
        }
        assert!(
            data.join("e2e_w/parent/photo1.jpg").exists(),
            "file should exist: e2e_w/parent/photo1.jpg"
        );
        assert!(
            !data.join("e2e_w/photo1.jpg").exists(),
            "file should be absent: e2e_w/photo1.jpg"
        );
        assert!(
            data.join("e2e_w/parent/photo2.jpg").exists(),
            "file should exist: e2e_w/parent/photo2.jpg"
        );
        assert!(
            !data.join("e2e_w/photo2.jpg").exists(),
            "file should be absent: e2e_w/photo2.jpg"
        );
        assert!(
            data.join("e2e_w/parent/vacation").exists(),
            "file should exist: e2e_w/parent/vacation"
        );
    }

    #[test]
    fn complex_photo_moves_between_albums_verified_via_api_and_filesystem() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_x/album_a")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_x/album_a/.__urocissa_ph__.jpg"),
            path_color("e2e_x/album_a/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_x/album_b")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_x/album_b/.__urocissa_ph__.jpg"),
            path_color("e2e_x/album_b/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_x/import")).expect("create dir");
        write_real_jpeg(
            &data.join("e2e_x/import/photo.jpg"),
            path_color("e2e_x/import/photo.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let album_a = discover_album_id(&client, "e2e_x/album_a");
        let album_b = discover_album_id(&client, "e2e_x/album_b");
        let photo = discover_photo_hash(&client, "e2e_x/import/photo.jpg");
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album_a, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album_b, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
        let resp_2 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_2.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_3 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_3.status(),
            Status::from_code(200).unwrap(),
            "call resp_3 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_3.into_bytes().expect("response body"))
                .expect("valid JSON");
        assert_eq!(
            parsed_final[0]["abstractData"]["album"],
            serde_json::json!(album_b),
            "response.json.[0].abstractData.album mismatch"
        );
        assert!(
            data.join("e2e_x/album_b/photo.jpg").exists(),
            "file should exist: e2e_x/album_b/photo.jpg"
        );
        assert!(
            !data.join("e2e_x/album_a/photo.jpg").exists(),
            "file should be absent: e2e_x/album_a/photo.jpg"
        );
        assert!(
            !data.join("e2e_x/import/photo.jpg").exists(),
            "file should be absent: e2e_x/import/photo.jpg"
        );
    }

    #[test]
    fn complex_tags_and_album_survive_assign_and_reindex() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_y/album")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_y/album/.__urocissa_ph__.jpg"),
            path_color("e2e_y/album/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_y/import")).expect("create dir");
        write_real_jpeg_with_xmp_and_exif(
            &data.join("e2e_y/import/sunset.jpg"),
            [128, 128, 128],
            &["e2e_y_scenic", "e2e_y_sunset"],
            Some("2025:06:15 19:30:00"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let album = discover_album_id(&client, "e2e_y/album");
        let photo = discover_photo_hash(&client, "e2e_y/import/sunset.jpg");
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_1.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_2 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_2.status(),
            Status::from_code(200).unwrap(),
            "call resp_2 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_2.into_bytes().expect("response body"))
                .expect("valid JSON");
        assert_eq!(
            parsed_final[0]["abstractData"]["album"],
            serde_json::json!(album),
            "response.json.[0].abstractData.album mismatch"
        );
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_y_scenic".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_y_scenic"
        );
        let resp_3 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_3.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let resp_4 = client
            .post("/put/reindex")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(format!(r#"{{"indexArray":[{idx}],"timestamp":{ts}}}"#))
            .dispatch();
        assert_eq!(
            resp_4.status(),
            Status::from_code(200).unwrap(),
            "call resp_4 status"
        );
        let resp_5 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_5.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_6 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_6.status(),
            Status::from_code(200).unwrap(),
            "call resp_6 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_6.into_bytes().expect("response body"))
                .expect("valid JSON");
        assert_eq!(
            parsed_final[0]["abstractData"]["album"],
            serde_json::json!(album),
            "response.json.[0].abstractData.album mismatch"
        );
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_y_scenic".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_y_scenic"
        );
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_y_sunset".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_y_sunset"
        );
        assert!(
            data.join("e2e_y/album/sunset.jpg").exists(),
            "file should exist: e2e_y/album/sunset.jpg"
        );
        assert!(
            !data.join("e2e_y/import/sunset.jpg").exists(),
            "file should be absent: e2e_y/import/sunset.jpg"
        );
    }

    #[test]
    fn create_dir_album_creates_subdirectory_and_registers_album() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        let data_path = data.to_string_lossy().to_string();
        std::fs::create_dir_all(&data.join("e2e_create_dir_album/parent"))
            .expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_create_dir_album/parent/.__urocissa_ph__.jpg"),
            path_color("e2e_create_dir_album/parent/.__urocissa_ph__.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let parent = discover_album_id(&client, "e2e_create_dir_album/parent");
        let resp_0 = client
            .post("/post/create_dir_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(
                serde_json::json!({"name": "child".to_string(), "parentAlbumId": parent})
                    .to_string(),
            )
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .get("/get/get-albums")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_1.into_bytes().expect("response body"))
                .expect("valid JSON");
        let found = parsed_final
            .as_array()
            .expect("response must be an array")
            .iter()
            .find(|item| {
                item["dirPath"]
                    == serde_json::json!(
                        data_path.clone() + &"/e2e_create_dir_album/parent/child".to_string()
                    )
            })
            .expect("no element matching array_where conditions");
        assert_eq!(
            found["parentAlbumId"],
            serde_json::json!(parent),
            "array_where parentAlbumId mismatch"
        );
        assert!(
            data.join("e2e_create_dir_album/parent/child").exists(),
            "file should exist: e2e_create_dir_album/parent/child"
        );
    }

    #[test]
    fn create_empty_album_endpoint_removed() {
        let client = make_client();
        let resp = client
            .post("/post/create_empty_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(404).unwrap(),
            "call resp status"
        );
    }

    #[test]
    fn dir_album_parent_child_relationship() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        let data_path = data.to_string_lossy().to_string();
        std::fs::create_dir_all(&data.join("e2e_d")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_d/.__urocissa_ph__.jpg"),
            path_color("e2e_d/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_d/vacation")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_d/vacation/.__urocissa_ph__.jpg"),
            path_color("e2e_d/vacation/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_d/vacation/day1")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_d/vacation/day1/.__urocissa_ph__.jpg"),
            path_color("e2e_d/vacation/day1/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_d/vacation")).expect("create dir");
        write_real_jpeg_with_xmp_keywords(
            &data.join("e2e_d/vacation/img1.jpg"),
            [128, 128, 128],
            &["e2e_d_travel"],
        );
        std::fs::create_dir_all(&data.join("e2e_d/vacation/day1")).expect("create dir");
        write_real_jpeg_with_xmp_keywords(
            &data.join("e2e_d/vacation/day1/img2.jpg"),
            [128, 128, 128],
            &["e2e_d_travel", "e2e_d_beach"],
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let e2e_id = discover_album_id(&client, "e2e_d");
        let parent_id = discover_album_id(&client, "e2e_d/vacation");
        let child_id = discover_album_id(&client, "e2e_d/vacation/day1");
        let resp_0 = client
            .get("/get/get-albums")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_0.into_bytes().expect("response body"))
                .expect("valid JSON");
        let found = parsed_final
            .as_array()
            .expect("response must be an array")
            .iter()
            .find(|item| {
                item["dirPath"] == serde_json::json!(data_path.clone() + &"/e2e_d".to_string())
            })
            .expect("no element matching array_where conditions");
        assert_eq!(
            found["albumId"],
            serde_json::json!(e2e_id),
            "array_where albumId mismatch"
        );
        assert_eq!(
            found["dirPath"],
            serde_json::json!(data_path.clone() + &"/e2e_d".to_string()),
            "array_where dirPath mismatch"
        );
        assert_eq!(
            found["parentAlbumId"],
            serde_json::json!(null),
            "array_where parentAlbumId mismatch"
        );
        let found = parsed_final
            .as_array()
            .expect("response must be an array")
            .iter()
            .find(|item| {
                item["dirPath"]
                    == serde_json::json!(data_path.clone() + &"/e2e_d/vacation".to_string())
            })
            .expect("no element matching array_where conditions");
        assert_eq!(
            found["albumId"],
            serde_json::json!(parent_id),
            "array_where albumId mismatch"
        );
        assert_eq!(
            found["dirPath"],
            serde_json::json!(data_path.clone() + &"/e2e_d/vacation".to_string()),
            "array_where dirPath mismatch"
        );
        assert_eq!(
            found["parentAlbumId"],
            serde_json::json!(e2e_id),
            "array_where parentAlbumId mismatch"
        );
        let found = parsed_final
            .as_array()
            .expect("response must be an array")
            .iter()
            .find(|item| {
                item["dirPath"]
                    == serde_json::json!(data_path.clone() + &"/e2e_d/vacation/day1".to_string())
            })
            .expect("no element matching array_where conditions");
        assert_eq!(
            found["albumId"],
            serde_json::json!(child_id),
            "array_where albumId mismatch"
        );
        assert_eq!(
            found["dirPath"],
            serde_json::json!(data_path.clone() + &"/e2e_d/vacation/day1".to_string()),
            "array_where dirPath mismatch"
        );
        assert_eq!(
            found["parentAlbumId"],
            serde_json::json!(parent_id),
            "array_where parentAlbumId mismatch"
        );
    }

    #[test]
    fn image_serving_survives_album_move() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_v/album")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_v/album/.__urocissa_ph__.jpg"),
            path_color("e2e_v/album/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_v")).expect("create dir");
        write_real_jpeg(&data.join("e2e_v/photo.jpg"), path_color("e2e_v/photo.jpg"));
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let album = discover_album_id(&client, "e2e_v/album");
        let photo = discover_photo_hash(&client, "e2e_v/photo.jpg");
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        assert_eq!(
            serve_compressed_image(&client, &photo),
            Status::Ok,
            "serve_image_ok: $photo"
        );
    }

    #[test]
    fn path_completion_returns_absolute_paths() {
        let client = make_client();
        let resp_0 = client
            .get("/get/path-completion")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_0.into_bytes().expect("response body"))
                .expect("valid JSON");
        for child in parsed_final["children"]
            .as_array()
            .expect("response.json.children must be an array")
        {
            let path = child.as_str().expect("child must be a string");
            assert!(
                std::path::Path::new(path).is_absolute(),
                "expected absolute path, got {path}"
            );
        }
        let resp_1 = client
            .get("/get/path-completion?path=src")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_1.into_bytes().expect("response body"))
                .expect("valid JSON");
        for child in parsed_final["children"]
            .as_array()
            .expect("response.json.children must be an array")
        {
            let path = child.as_str().expect("child must be a string");
            assert!(
                std::path::Path::new(path).is_absolute(),
                "expected absolute path, got {path}"
            );
        }
    }

    #[test]
    fn photo_tags_reflect_injected_metadata() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_b/2023/summer")).expect("create dir");
        write_real_jpeg_with_xmp_and_exif(
            &data.join("e2e_b/2023/summer/beach.jpg"),
            [128, 128, 128],
            &["e2e_b_nature", "e2e_b_summer", "e2e_b_beach"],
            Some("2023:07:15 10:00:00"),
        );
        std::fs::create_dir_all(&data.join("e2e_b/2023/summer")).expect("create dir");
        write_real_jpeg_with_xmp_and_exif(
            &data.join("e2e_b/2023/summer/sunset.jpg"),
            [128, 128, 128],
            &["e2e_b_nature", "e2e_b_summer"],
            Some("2023:07:16 20:00:00"),
        );
        std::fs::create_dir_all(&data.join("e2e_b/2024/winter")).expect("create dir");
        write_real_jpeg_with_xmp_and_exif(
            &data.join("e2e_b/2024/winter/snow.jpg"),
            [128, 128, 128],
            &["e2e_b_nature", "e2e_b_winter"],
            Some("2024:01:10 09:00:00"),
        );
        std::fs::create_dir_all(&data.join("e2e_b/2024/city")).expect("create dir");
        write_real_jpeg_with_xmp_keywords(
            &data.join("e2e_b/2024/city/skyline.jpg"),
            [128, 128, 128],
            &["e2e_b_architecture", "e2e_b_city"],
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let resp_0 = client
            .get("/get/get-tags")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_0.into_bytes().expect("response body"))
                .expect("valid JSON");
        let tags = parsed_final.as_array().expect("response must be an array");
        for (tag, min) in [
            ("e2e_b_architecture", 1u64),
            ("e2e_b_beach", 1u64),
            ("e2e_b_city", 1u64),
            ("e2e_b_nature", 3u64),
            ("e2e_b_summer", 2u64),
            ("e2e_b_winter", 1u64),
        ] {
            let got = tags
                .iter()
                .find(|t| t["tag"].as_str() == Some(tag))
                .and_then(|t| t["number"].as_u64())
                .unwrap_or(0);
            assert!(got >= min, "tag '{tag}': expected >= {min}, got {got}");
        }
    }

    #[test]
    fn read_only_mode_blocks_mutating_routes() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        write_config(&serde_json::json!({ "read_only_mode": true }));
        let client = make_client();
        let resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/".to_string()}).to_string())
            .dispatch();
        assert_eq!(
            resp.status(),
            Status::from_code(405).unwrap(),
            "call resp status"
        );
        write_config(&serde_json::json!({"read_only_mode": false}));
    }

    #[test]
    fn reindex_preserves_album_and_tags() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_s_album")).expect("create album dir");
        write_real_jpeg(
            &data.join("e2e_s_album/.__urocissa_ph__.jpg"),
            path_color("e2e_s_album/.__urocissa_ph__.jpg"),
        );
        std::fs::create_dir_all(&data.join("e2e_s_import")).expect("create dir");
        write_real_jpeg(
            &data.join("e2e_s_import/e2e_s_photo.jpg"),
            path_color("e2e_s_import/e2e_s_photo.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let album = discover_album_id(&client, "e2e_s_album");
        let photo = discover_photo_hash(&client, "e2e_s_import/e2e_s_photo.jpg");
        let resp_0 = client
            .put("/put/assign_album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"albumId": album, "hash": photo}).to_string())
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        let resp_1 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_1.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let resp_2 = client
            .put("/put/edit_tag")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(format!(r#"{{"indexArray":[{idx}],"addTagsArray":["e2e_s_keep_me"],"removeTagsArray":[],"timestamp":{ts}}}"#))
            .dispatch();
        assert_eq!(
            resp_2.status(),
            Status::from_code(200).unwrap(),
            "call resp_2 status"
        );
        let resp_3 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_3.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let resp_4 = client
            .post("/put/reindex")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(format!(r#"{{"indexArray":[{idx}],"timestamp":{ts}}}"#))
            .dispatch();
        assert_eq!(
            resp_4.status(),
            Status::from_code(200).unwrap(),
            "call resp_4 status"
        );
        let resp_5 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_5.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_6 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_6.status(),
            Status::from_code(200).unwrap(),
            "call resp_6 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_6.into_bytes().expect("response body"))
                .expect("valid JSON");
        assert_eq!(
            parsed_final[0]["abstractData"]["album"],
            serde_json::json!(album),
            "response.json.[0].abstractData.album mismatch"
        );
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_s_keep_me".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_s_keep_me"
        );
    }

    #[test]
    fn tags_modifiable_via_edit_tag_api() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_p")).expect("create dir");
        write_real_jpeg(&data.join("e2e_p/photo.jpg"), path_color("e2e_p/photo.jpg"));
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let photo = discover_photo_hash(&client, "e2e_p/photo.jpg");
        let resp_0 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_0.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let resp_1 = client
            .put("/put/edit_tag")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(format!(r#"{{"indexArray":[{idx}],"addTagsArray":["e2e_p_added"],"removeTagsArray":[],"timestamp":{ts}}}"#))
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
        let resp_2 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_2.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_3 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_3.status(),
            Status::from_code(200).unwrap(),
            "call resp_3 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_3.into_bytes().expect("response body"))
                .expect("valid JSON");
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_p_added".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_p_added"
        );
    }

    #[test]
    fn tags_visible_via_get_data() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("e2e_o")).expect("create dir");
        write_real_jpeg_with_xmp_keywords(
            &data.join("e2e_o/tagged.jpg"),
            [128, 128, 128],
            &["e2e_o_family", "e2e_o_vacation"],
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let photo = discover_photo_hash(&client, "e2e_o/tagged.jpg");
        let resp_0 = client
            .post(format!(r#"/get/prefetch?locate={photo}"#))
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .dispatch();
        let parsed_body: serde_json::Value =
            serde_json::from_slice(&resp_0.into_bytes().expect("response body")).unwrap();
        let idx = {
            let val = &parsed_body["prefetch"]["locateTo"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let token = {
            let val = &parsed_body["token"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let ts = {
            let val = &parsed_body["prefetch"]["timestamp"];
            val.as_str()
                .map(|s| s.to_string())
                .unwrap_or_else(|| val.to_string())
        };
        let end = (idx.parse::<i64>().unwrap() + 1).to_string();
        let resp_1 = client
            .get(format!(
                r#"/get/get-data?timestamp={ts}&start={idx}&end={end}"#
            ))
            .header(rocket::http::Header::new(
                "Authorization",
                "Bearer ".to_string() + &token.clone(),
            ))
            .dispatch();
        assert_eq!(
            resp_1.status(),
            Status::from_code(200).unwrap(),
            "call resp_1 status"
        );
        let parsed_final: serde_json::Value =
            serde_json::from_slice(&resp_1.into_bytes().expect("response body"))
                .expect("valid JSON");
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_o_family".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_o_family"
        );
        let arr = parsed_final[0]["abstractData"]["tags"]
            .as_array()
            .expect("response.json.[0].abstractData.tags must be an array");
        assert!(
            arr.contains(&serde_json::json!("e2e_o_vacation".to_string())),
            "response.json.[0].abstractData.tags does not contain e2e_o_vacation"
        );
    }

    #[test]
    fn watcher_discovers_new_file_in_subdirectory() {
        let _ = &*TEST_ENV;
        let data = test_image_home();
        set_image_home(data.clone());
        std::fs::create_dir_all(&data.join("watcher_import")).expect("create dir");
        write_real_jpeg(
            &data.join("watcher_import/photo.jpg"),
            path_color("watcher_import/photo.jpg"),
        );
        let client = make_client();
        let _guard = INDEX_SERIAL_GUARD.lock().unwrap_or_else(|e| e.into_inner());
        let _scan_resp = client
            .post("/post/index/album")
            .cookie(auth_cookie(&client))
            .header(ContentType::JSON)
            .body(serde_json::json!({"album": "/"}).to_string())
            .dispatch();
        assert_eq!(_scan_resp.status(), Status::Accepted, "scan trigger");
        wait_for_album_index(&client, 30000);
        let photo = discover_photo_hash(&client, "watcher_import/photo.jpg");
        let resp_0 = client
            .get("/get/get-albums")
            .cookie(auth_cookie(&client))
            .dispatch();
        assert_eq!(
            resp_0.status(),
            Status::from_code(200).unwrap(),
            "call resp_0 status"
        );
        assert!(
            data.join("watcher_import/photo.jpg").exists(),
            "file should exist: watcher_import/photo.jpg"
        );
    }
}
